### ISSUE TITLE
tF4Health

### ISSUE THREAD

**Issue by ulahealth** [open-austin/project-ideas#100]
### What problem are we trying to solve?
healthcare disruption group is seeking to empower patients to control their healthcare information more cohesively such as basic electronic healthcare/medical records, insurance coverage/plan information, medication compliance; the healthcare system(s) are broken and exist in too many silos to the detriment of patients and providers thus increasing everyone's healthcare costs; we are seeking to develop a blockchain strategy around one or multiple issues

### Who will benefit (directly and indirectly) from this project?
Patients will benefit first and foremost, patient-centric UI/UX is imperative for this project

### Links to any research/data available/articles
more to come here, we have a ton

### What are the next steps (validation, research, coding, design)? 
we have validation, and done significant research, we need assistance with blockchain strategy coding and design

### What help is needed at this time?
strategy development around how to best implement a blockchain solution to manage some not all of the personal health information

**Comment by cjessett** [comment]
have y'all checked out https://patientory.com/

**Comment by mscarey** [comment]
Closing because it doesn't seem like there's a way forward for this concept.
