### ISSUE TITLE
Does any one need UI/UX help? Ping me

### ISSUE THREAD

**Issue by joshavenue** [open-austin/project-ideas#113]
Does anyone here need UI/UX (Mobile and website design) help? Here is my portfolio : http://zensite.design
Call : https://calendly.com/zensite/call
![capture](https://user-images.githubusercontent.com/30822255/31319157-e69bb862-ac90-11e7-812d-88da23d33bbb.PNG)

**Comment by werdnanoslen** [comment]
hi @joshavenue, this repo is for project ideas. If you see a project you're interested in, could you please respond to those issues? I'm going to close this for now, but if you have a project idea, feel free to post again :)

**Comment by werdnanoslen** [comment]
hi @joshavenue, this repo is for project ideas. If you see a project you're interested in, could you please respond to those issues? I'm going to close this for now, but if you have a project idea, feel free to post again :)
