### ISSUE TITLE
Austin Park Equity

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/project-ideas#12]
**One sentence description**: 
A interactive map that shows areas with the least park access and the most need based on demographic data.

**Link (more details/brain dump/alpha)**
https://github.com/open-austin/Austin_Parks_Equity
http://open-austin.github.io/Austin_Parks_Equity/

**Project Needs (dev/design/resources)**
d3, leaflet, or turf experience

**Status (in progress, pie-in-the-sky)**
in progress

**Comment by mscarey** [comment]
This seems done. See [austinparkequity.com](http://austinparkequity.com/).
