### ISSUE TITLE
[OH HOLD] Fireboard: An app to help the Austin Fire Department with scheduling issues 🔥

### ISSUE THREAD

**Issue by danielryne** [open-austin/project-ideas#121]
### What problem are we trying to solve?

The Austin Fire Department has over 50 stations and hundreds of firefighters and staff. Every day, the Fire Battalion Chiefs take about an hour and half each to manage their battalion locations by strategizing staff schedules (leaves - sick, vacations, etc.). If they are unable to fill their battalion, they coordinate with other Battalion Chiefs.  

So we're helping them convert a shift board (an actual whiteboard with magnets!) to a web-app which integrates with AFD’s existing databases.

### Who will benefit (directly and indirectly) from this project?

Austin Fire Department and everyone who benefits from them. 🚒 👩🏽‍🚒 

### What help is needed at this time?

We need help building out the prototype in time for Hack for Change! We've got a framework put together and [Git here](https://github.com/danielryne/fireboard) and [deployed here](https://fireboard-app.herokuapp.com/). 

We need help building out and designing various features:

- input validation 
- export functionality (being able to export a CSV or something like that)
- sorting and searching 
- communication functionality (being able to email to a 

### How can we contact you outside of Github?

Get at us on the Open Austin [Slack channel](https://slack.open-austin.org/): **p-fireboard**

### Current Contributors
- [Daniel Ryne Lucio](https://github.com/danielryne?tab=repositories) 
- [Forrest Eastland](https://github.com/eastman81) 
- [James Doss](https://github.com/jadoss) 
- [Jesse Reitz](https://github.com/jessereitz)

**Comment by johnvanlowe** [comment]
Possible to implement methods from other open source tools (not fire dept specific)? Maybe just food for thought on other methods:

https://www.staffjoy.com/
https://github.com/staffjoy

http://www.openskedge.org/
https://github.com/OfficeStack/OpenSkedge

**Comment by danielryne** [comment]
Thanks @johnvanlowe ! As it turns out, the Fire Department will be piloting a whiteboard system with Kronos using their Telestaff product. I think they had been working on a scope of work with them since last year, but didn't think it would include a shifting/whiteboard system. 

So, that means that this pilot makes any work that we do on this project irrelevant (in my opinion) until they've finished the pilot - a year or so from now. So I don't think taking this project forward would be a good use of folks' time, at least while the city pursues their own project. I'm going to mark the project as inactive, and move to another one soon. 

However, if folks still want to work on this, I'm happy to meet with them and walk them through the problem statement, the prototype and any of the work we've done. The repo is also cloneable if folks want to play around with what we have.

**Comment by mscarey** [comment]
Closing, but feel free to reopen @danielryne if you have anything to add

**Comment by danielryne** [comment]
Thanks y'all!
