### ISSUE TITLE
Texas Appleseed (school-to-prison pipeline)

### ISSUE THREAD

**Issue by MCraven2800** [open-austin/project-ideas#14]
### [The repo for this project lives here](https://github.com/txappleseed/txappleseedmap)

**One sentence description**: 

As part of our efforts to dismantle the school-to-prison pipeline (the policies and practices that push kids out of school through suspensions, expulsions, alternative school placements, and police contact) we want to create a website that provides practical resources, interactive maps, and data collection tools to students, parents, grassroots organizations, advocates, and school districts who want to make positive changes in their schools and communities.

Please see description below for more details . . .

**Link (more details/brain dump/alpha)**

This is a link to what we do:  https://www.texasappleseed.org/school-prison-pipeline

**Project Needs (dev/design/resources)**

We need everything: development, design vision, actual design, resources, etc.

**Status (in progress, pie-in-the-sky)**

We have collected and developed the resources that will be on the site, are in the process of collecting student arrest, ticketing, and school discipline data, and have started putting feelers out for people who can help.

Microsite Purpose:
1. To provide an online space where students, parents, community organizations, and school districts can easily access practical information and resources related to school discipline and the school-to- prison pipeline. There would be a link to the site on the Texas Appleseed website’s School-to-Prison Pipeline Project page. Ex. The Advancement Project’s “Ending the Schoolhouse to Jailhouse Track” microsite that is linked directly to The AP’s main page. http://safequalityschools.org/
2. To track incidents and data related to school discipline (including exclusionary discipline and arrest data and media stories related to uses of excessive force by school police, arrests, pepper spray, tasers, etc.) so that (1) site visitors are aware of what is going on in their districts and (2) Texas Appleseed can continuously compile and publish incident reports and data. Ex. The Southern Poverty Law Center’s Hate Incidents Tracker. http://www.splcenter.org/get-informed/hate-incidents
3. To provide a space where individuals can rate their school districts and share their stories related to school discipline, with the purposes of (1) providing quantitative and qualitative data to Texas Appleseed and (2) allowing individuals and groups to see when there are district-wide problems so that they can organize community organizations to address them.  Ex. The Advancement Project’s Give Your School a Report Card Project. http://www.advancementproject.org/page/s/report-card?source=ema_adv_2015-05-12_ap_
   actives

A basic site would have:
1. Four different links—for students, parents, community organizations, and school districts—to downloadable documents, including “Know Your Rights” resources, infographics, explanations of changes in the law, toolkits, videos, etc.
2. A form for families to fill out to share their stories with us (linked directly to an excel spreadsheet for easy
   tracking).
3. The same general style as the Texas Appleseed site.

A dream site would also have:
1. An interactive map that would allow users to search for data sets (e.g., number of suspensions, disaggregated by race, special education status, etc.) in different regions/districts in Texas.  Ex.  http://www.diversitydatakids.org/data/map
2. The option for Texas Appleseed staff to easily input data from multiple sources---spreadsheets, media reports, student stories, etc.
3. A space for families to rate their schools, tell stories, and have the ratings/stories automatically pop up on a map that would indicate when there are “hotspots” of high numbers of stories or particularly bad ratings.
4. A space for community organizations to share success stories and best practices, with the purpose of encouraging other parent groups to grow across the state.

**Comment by luqmaan** [comment]
Can you narrow the scope of this project?

There are too many things.

**Comment by MCraven2800** [comment]
I'd be happy to, but please give me a little more guidance.  There are too
many of what things?  Too many needs (development, resources, etc)?  Or too
much in my description of what we want to create?

On Tue, Jul 14, 2015 at 9:44 AM, Luqmaan Dawoodjee <notifications@github.com
> wrote:

> Can you narrow the scope of this project?
>
> There are too many things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-austin/project-ideas/issues/14#issuecomment-121259030>
> .
>



-- 
Morgan Craven
Director, School-to-Prison Pipeline Project
Texas Appleseed
512.473.2800 ext.110
www.texasappleseed.net

**Comment by luqmaan** [comment]
Awesome!

Sorry I wasn't clear, I meant to say that you want to make too many things. Based on the current description it looks like there are three projects.

> we want to create a website that provides practical resources, interactive maps, and data collection tools

Can you describe what you want to do with each of these in more detail?

----------------------------

1. > website that provides practical resources

  What sort of resources would the website provide that aren't already on https://www.texasappleseed.org/school-prison-pipeline?

2. > interactive maps

 Maps of what?

3. > data collection tools
 
 What data would you like to collect?

--------------------------------

I'd like to narrow this issue down to a single project. This makes it easier for people interested in contributing to know where to start.

**Comment by mateoclarke** [comment]
Just to add on here to what @luqmaan is getting at (I think)...

There's no reason the end product couldn't be contained in a single webapp/site. But in order to tackle the bigger problem in pieces and to understand the scope of each and how it all fits together, it's helpful to break out the features of the site more thoroughly. This will at least give folks a good starting point and prioritized list of what to work on.

**Comment by MCraven2800** [comment]
I think I understand, thanks!   In order to do this, I am going to violate
the one sentence limit . . .

On Tue, Jul 14, 2015 at 10:23 AM, Mateo Clarke <notifications@github.com>
wrote:

> Just to add on here to what @luqmaan <https://github.com/luqmaan> is
> getting at (I think)...
>
> There's no reason the end product couldn't be contained in a single
> webapp/site. But in order to tackle the bigger problem in pieces and to
> understand the scope of each and how it all fits together, it's helpful to
> break out the features of the site more thoroughly. This will at least give
> folks a good starting point and prioritized list of what to work on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-austin/project-ideas/issues/14#issuecomment-121280848>
> .
>



-- 
Morgan Craven
Director, School-to-Prison Pipeline Project
Texas Appleseed
512.473.2800 ext.110
www.texasappleseed.net

**Comment by luqmaan** [comment]
:smiling_imp:

**Comment by mateoclarke** [comment]
Yeah, one sentence description is definitely subject removal... Good to be concise, but this project obviously needs more than a sentence.

**Comment by mateoclarke** [comment]
### _"Dismantle the Pipeline"_

If that's not already the tagline, it should be. :hammer:

**Comment by tgregoneil** [comment]
Possible new item in Microsite Purpose:

4.  To facilitate advocacy for after-school programs such as music, recreational sports, etc., that would provide constructive activities for students.

**Comment by MCraven2800** [comment]
Yes, I think that is great---thanks Greg!

On Wed, Jul 15, 2015 at 4:15 AM, tgregoneil <notifications@github.com>
wrote:

> Possible new item in Microsite Purpose:
>
>    1. To facilitate advocacy for after-school programs such as music,
>    recreational sports, etc., that would provide constructive activities for
>    students.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-austin/project-ideas/issues/14#issuecomment-121542160>
> .
>



-- 
Morgan Craven
Director, School-to-Prison Pipeline Project
Texas Appleseed
512.473.2800 ext.110
www.texasappleseed.net

**Comment by MCraven2800** [comment]
I actually really really like that.  I've always liked that phrase when we
use it in our materials, and I love the idea of pulling it out and
highlighting it as a tagline.

On Wed, Jul 15, 2015 at 12:54 AM, Mateo Clarke <notifications@github.com>
wrote:

> *"Dismantle the Pipeline"*
>
> If that's not already the tagline, it should be. [image: :hammer:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-austin/project-ideas/issues/14#issuecomment-121498747>
> .
>



-- 
Morgan Craven
Director, School-to-Prison Pipeline Project
Texas Appleseed
512.473.2800 ext.110
www.texasappleseed.net

**Comment by PatiSilva** [comment]
Here's an example of site: http://mappingpoliceviolence.org/
I like that the facts are listed on the side and the interesting and attention grabbing things they did with the map and the graph.

**Comment by luqmaan** [comment]
@MCraven2800 You should identify **one** thing that you think is ready for people to start working on.

Some of the projects you have now:

1. **A basic site** with four sections: students, parents, community organizations, and school districts. Each section has links to other resources. The site will follow the same style as Texas Appleseed.
2. **A form for families** to fill out to share their stories with us.
3. **An interactive map** that would allow users to search for data sets (e.g., number of suspensions, disaggregated by race, special education status, etc.) in different regions/districts in Texas. Ex. http://www.diversitydatakids.org/data/map
  - To start this project you're going to need a spreadsheet of all the potential datasets you'd like to use. If there aren't enough good datasets available, this idea isn't feasible.
4. **A space for families to rate their schools**, tell stories, and have the ratings/stories automatically pop up on a map 

So which **one** project do you want people to work on?

**Comment by MCraven2800** [comment]
If I HAVE to choose one :)  I choose #1: A basic site with resources.  

I will add that part of the beauty of the idea is that it is, essentially, two-way data sharing---we will provide resources (#1) but we will also collect stories and data from the people who access the site (#s 2 & 3) and present the information back to them in a way that is easy to understand (# 4).  All the parts listed above are closely linked.  I got the sense from the group that met last week that this two-way sharing was one of the most appealing and challenging parts of the project.  Sorry Luqmaan, I couldn't resist elaborating, but I wanted to make the project a little bit more clear.

**Comment by luqmaan** [comment]
:+1: Thanks for choosing one and elaborating @MCraven2800.

The other projects are great ideas as well. But now we know which one to start with.

**Comment by johntyree** [comment]
Had a meeting this evening about what's available now and where we could take this. We should probably break out into a repo soon.

# Resource Provision / Sharing Site
  #### Goals
  - Educate and motivate students and parents
  - Encourage/facilitate community group formation

## Design
  - Landing page - Call to action
    - Personal story?
    - Inspirational impact thus far?
        - E.g. impact of truancy decriminalization?
  - Site will be standalone but should have Texas Appleseed logo/branding
  - ##### First steps are to mock a site with look-and-feel like safequalityschools.org
    - Focus more on Texas, specifically
    - Include some *simple* visualizations of eye catching data
    - Talk to data wrangler Yamanda (ywright@texasappleseed.net) about content


## Site content
  - Compelling visualizations of interesting "data stories" (see below)
    - Important for showing during the 2017 legislative session
  - Digestible summaries of important policy issues
  - Example resources:
    - https://www.texasappleseed.org/resources?field_featured_value=All&field_status_value=All&field_multi_project_association_target_id_entityreference_filter=76&field_status_value_1_op=or&field_status_value_1=All
    - Would like to present these in a more accessible way
  - Specialize presentation for cohorts (Students, Parents, Community Leaders)

# Currently Available Data:
#### Comes in two flavors
- ##### Disciplinary actions
  - Number of students affected by (ISS, OSS, Expulsion, etc)
  - At the individual student level (race, socioeconomic status)
    - anonymized into small groups (min 5 students) 
  - At the school level
  - At the district level
  - Data goes back to ~2005 or so (including partial data)
  - More data at: http://tea.texas.gov/Reports_and_Data/

- ##### Police interactions (both school & city PD)
  - Ample case data
    - Not always well anonymized
    - Much of it is geocoded
  - Would like to be able to map and filter data by demographic:
    - E.g. Allow parents to view stats for kids similar to their own

#### Motivate advocacy positions
- The One True Goal® is to dismantle the pipeline. The data will help identify how to do that effectively.
- Important for presenting at 2017 legislative session
#### Extract compelling stories
- E.g. Relationship between discipline data and housing
- Would be interesting to tie any of this to assessment / achievement
  - Effect of "teaching to the test" on student behavior
  - Teacher quality? (young, inexperienced teachers)
    - Unable to handle disciplinary issues
    - Often lean on unfair / unreasonable (but easy) methods
  - Class sizes?
  - School sizes?
- Create indices that summarize/combine issues
  - Helps users find meaning in complicated data
  - Very amenable to mapping
  - Ex: Safety index heat map
    - arrests per block
    - officers per block
    - parks per block
  - Ex: Child opportunity index
    - http://www.diversitydatakids.org/data/childopportunitymap
    - http://www.diversitydatakids.org/data/childopportunitymap/3328/dallas-fort-worth-arlington

## Gathering New Data
-  Have users submit data about what's going on in a district
    - Helps cover gaps in data collection
    - Is very fast.
    - twitter?
    - facebook?
    - youtube?
    - vine?
    - snapchat?
    - imgur?
  - Provides evidence for show-and-tell during 2017 legislative session
  - Helps identify relevant lawsuits / plaintiffs for lawsuits
  - Helps identify ways to *avoid* lawsuits via other means of intervention

**Comment by PatiSilva** [comment]
Need assistance modifying the text on the attached image for the logo.  The title: School Discipline should be replaced by Texas School Discipline Lab. Styling stays the same.
![tx-appleseed-logo](https://cloud.githubusercontent.com/assets/4556185/13440870/ee5ee39e-dfb9-11e5-9f0a-a7e84495a9d5.jpg)
https://github.com/open-austin/project-ideas/labels/help%20wanted

**Comment by VictoriaODell** [comment]
@PatiSilva do you have the ai file for this or know the font?

**Comment by johntyree** [comment]
We actually took care of this tonight with the help of @amaliebarras!

**Comment by VictoriaODell** [comment]
sweet~ I just saw this.

**Comment by amaliebarras** [comment]
@victoriaodell but fyi it’s called museo slab 300! sharing bc it’s cute & maybe you like it also

**Comment by PatiSilva** [comment]
I don’t know the font since it is an image.

**Comment by PatiSilva** [comment]
Thank you so much.  I just got home about 15 minutes ago.  Thank you @amaliebarras <https://github.com/amaliebarras>!

**Comment by mateoclarke** [comment]
https://github.com/txappleseed/txappleseedmap

**Comment by werdnanoslen** [comment]
who is/are the lead(s) for this project?

**Comment by 305kev** [comment]
Hey y'all, could some one comment on what still needs to be done, or what new avenues we could take with this tomorrow at the Civic Hack?

**Comment by mscarey** [comment]
This project still has ongoing maintenance needs, but I doubt we should try to onboard new people, and I don't think this thread is helpful anymore.
