### ISSUE TITLE
Austin projects that use CitySDK from US Census Bureau

### ISSUE THREAD

**Issue by jmeisel** [open-austin/project-ideas#16]
I'd like to find one or more existing Austin civic tech projects that could benefit from Census data:  http://uscensusbureau.github.io/citysdk/

It would be great to highlight Austin examples in the Open Data Solutions National Challenge, with submissions due July 31st:
https://www.challenge.gov/challenge/city-software-development-kit-sdk-data-solutions-challenge/

----------------------

Projects we will submit:

- Austin Parks Equity

**Comment by luqmaan** [comment]
What projects do we have that use the CitySDK or can use it?

@mateoclarke's Austin Parks Equity app definitely does.

**Comment by luqmaan** [comment]
:smile_cat:
