### ISSUE TITLE
Crowd Sourced Volunteering For Hurricane Ida

### ISSUE THREAD

**Issue by nicholasl** [open-austin/project-ideas#160]
Would some people like to join me in helping map people for hurricane rescue via crowdsourcerescue.org?

There are a lot of people stuck in attics that need to be added to the map for rescue overnight and tomm AM.

Apologies if there is a better place to post this too.

**Comment by lianilychee** [comment]
hey @nicholasl !  You'll reach FAR more people via Slack.  Only a tiny group checks (or is subscribed to) repo activity.

If you are looking for this to be a spike effort, I recommend:
1. Posting in the Code for America Slack, #brigade channel, for cross-brigade involvement ([sign up for CfA Slack here](https://docs.google.com/forms/d/e/1FAIpQLSfRqy9L8Z5bS8cPHmHrY6BPT5g6K45uo0Z3KicYLB4bsFp2wA/viewform))
2. Posting in the Open Austin Slack, #general #open-texas channels ([sign up for OA Slack here](https://slack.open-austin.org/))

If you are looking for this idea to have more longevity and robustness than a spike effort, submit a problem statement through the Google Form in the #oa-project-ideas channel description, and someone from our leadership will reach out, groom the idea with you, and determine if it's a good fit for our org.

**Comment by nicholasl** [comment]
Thank you for the insight there.
Nicholas
