### ISSUE TITLE
Bill Tracker

### ISSUE THREAD

**Issue by mcdermottsolutions** [open-austin/project-ideas#17]
**One sentence description:**
A webapp where you can read and annotate bills from the Texas legislature.

**Link:**
https://github.com/bill-tracker/bill-tracker
https://billtracker.slack.com

**Project Needs:**
We could use more:
Backend devs (python, django)
Frontend devs (html, css/sass, javascript, angular)
Designers
People with legal background/connections/interest
People with startup business background / non-profit funding background

**Status:**
In progress

**Comment by mateoclarke** [comment]
Very cool! Is there a public demo posted anywhere? Or maybe some early screenshots?

It would be cool if you added some specific issues to y'alls repo. Any specific tasks/features you have queued up?

**Comment by mcdermottsolutions** [comment]
We're developing locally at the moment. Hoping to deploy to Heroku or somewhere soon.

Here are some early screenshots:

<img width="1038" alt="screen shot 2015-07-16 at 2 08 51 pm" src="https://cloud.githubusercontent.com/assets/9694783/8732664/93cc6392-2bc4-11e5-9f5c-59711eabc49f.png">
<img width="1019" alt="screen shot 2015-07-16 at 2 10 21 pm" src="https://cloud.githubusercontent.com/assets/9694783/8732665/93cddcb8-2bc4-11e5-83b3-aa0f8c50bd68.png">
<img width="1031" alt="screen shot 2015-07-16 at 2 10 30 pm" src="https://cloud.githubusercontent.com/assets/9694783/8732702/b8eb9710-2bc4-11e5-9c22-e4926cf289fd.png">

**Comment by luqmaan** [comment]
You should deploy Bill Tracker ASAP, even if this early version is broken.

There's lots of reasons to make a live demo ASAP, but some important ones:

- It makes it easier for front end people to figure out where to contribute
- People can give you early feedback which you can iterate on before its too late
- Huge morale boost

**Comment by mcdermottsolutions** [comment]
Issues added! https://github.com/bill-tracker/bill-tracker/issues
We are hoping to deploy to heroku soon, maybe this weekend!

**Comment by edsfocci** [comment]
Live Demo:
http://billltracker.herokuapp.com/

**Comment by edsfocci** [comment]
Current landing page:
![Uploading BilllTracker-Home-2015-07-20.png…]()

**Comment by mateoclarke** [comment]
@mcdermottsolutions :+1: & @edsfocci :+1:

**Comment by luqmaan** [comment]
@mcdermottsolutions nice work!

I get 500s whenever I submit the form.

```
POST http://billltracker.herokuapp.com/bills/
    csrfmiddlewaretoken=yXQ9ytbVXbqik3OjkT3K3QnHexuDuITz
    session=84R
    chamber_origin=H
    number=20

Server Error (500)
```

**Comment by edsfocci** [comment]
Sorry about that, forgot to migrate the DB. It works now.

**Comment by luqmaan** [comment]
This is great!

Gonna link to this during the announcements section of tonight meetup http://billltracker.herokuapp.com/bills/HB120/

**Comment by edsfocci** [comment]
Cool @luqmaan!

**Comment by mcdermottsolutions** [comment]
We are live on http://www.billtracker.org/ now.  The domain's working for me here, but might take up to 24 hours to propagate everywhere.

**Comment by amaliebarras** [comment]
I just noticed that when I open this on my phone, it only shows the option for Senate bill and not House bill, is that supposed to happen?

Amalie

**Comment by mcdermottsolutions** [comment]
I noticed that too, definitely not supposed to happen. :grimacing: Things are a little broken right now on mobile - the capital building building background image isn't showing on my android either.  Adding to our issues now.

**Comment by amaliebarras** [comment]
Awesome! 

And hey congrats on the launch! How rude of me to jump straight to the bug and not acknowledge the enormous success :P

**Comment by mcdermottsolutions** [comment]
No, we definitely appreciate any bug reports! Thanks, we're getting there slowly but surely! :)

**Comment by luqmaan** [comment]
Closing this issue for now. Feel free to reopen.
