### ISSUE TITLE
Austin Recycles

### ISSUE THREAD

**Issue by luqmaan** [open-austin/project-ideas#18]
**Concise description**: 

An app that is location and calendar aware, that informs people of upcoming Austin Resource Recovery (ARR) collection services:

- trash and yard trimmings (weekly)
- recycling (bi-weekly)
- brush (bi-annual)
- bulky (bi-annual)

**Link (more details/brain dump/alpha)**

A prototype was implemented in 2013: http://austin-recycles.open-austin.org/

Austin Resource Recovery has provided a snapshot of service layers in proposed format:

- geospatial data
- provided as a SHP file

These layers have been imported into CartoDB:

- https://chipr.cartodb.com/tables/arr_service_recycle
- https://chipr.cartodb.com/tables/arr_service_bulky
- https://chipr.cartodb.com/tables/arr_service_brush

More project status at https://docs.google.com/presentation/d/10_SyFClmlkw3KusNbtuvms2ruxw3Jyk1pIQnfGjLt5I/edit?usp=sharing

**Project Needs (dev/design/resources)**

Re-implement app from scratch

- Evaluate CartoDB as alternate to custom data store and web service
- Develop visual design

Prefer to use tech currently used in other Open Austin projects

- Leaflet.js – open source mapping
- Knockout.js – simple JS framework, easy to pick up for newbies or experienced users of other frameworks
- Bootstrap – front-end framework

**Status (in progress, pie-in-the-sky)**

Needs contributors

*Details copy pastad from https://docs.google.com/presentation/d/10_SyFClmlkw3KusNbtuvms2ruxw3Jyk1pIQnfGjLt5I/edit#slide=id.p*

**Comment by mateoclarke** [comment]
ARR is using [Recollect](https://recollect.net/) to provide this functionality on iPhone and Android. I learned this in a meeting with ARR back in April. I think they plan to launch the apps in the fall. We could reconnect with them to learn more about this implementation or if there are still any needs.

They already have Recollect's "What Would I Do With" search feature rolled into their website:
http://www.austintexas.gov/department/austin-resource-recovery

**Comment by mateoclarke** [comment]
Didn't want to be a buzzkill (:bee: :gun:) but the city has opted to pay for a commercial product for this feature set and that should be known before anyone jumps into this as an open source project.

**Comment by chip-rosenthal** [comment]
I still thing we should do a simple single page app based on this that has an easy "add to calendar" feature. Once we've got the basic product, it can be a platform for community-initiated features.

**Comment by luqmaan** [comment]
Just so we know what the recollect thing does/will do:

###### wizard

http://jsfiddle.net/kyrc9n8g/2/

![image](https://cloud.githubusercontent.com/assets/1275831/8785401/1972245c-2eed-11e5-8168-aefb29f28be6.png)

![image](https://cloud.githubusercontent.com/assets/1275831/8785425/384a3e50-2eed-11e5-88af-93b277eedf5d.png)


###### page

looks like they're still working on this - http://jsfiddle.net/kyrc9n8g/3/

![image](https://cloud.githubusercontent.com/assets/1275831/8785393/0d2b9534-2eed-11e5-889f-113a1ae82fe1.png)

![image](https://cloud.githubusercontent.com/assets/1275831/8785445/465ec3b2-2eed-11e5-8d6b-ae3889acf4bf.png)

![image](https://cloud.githubusercontent.com/assets/1275831/8785446/4b7a519a-2eed-11e5-9dc7-c98679c4448a.png)

**Comment by luqmaan** [comment]
Since the Austin calendar doesn't work yet, here's one for Columbus:

https://311.columbus.gov/AddrLookupnew.aspx

https://recollect.net/api/places/9CA8F3CC-30A3-11E3-8252-114F1BEEAB8B/services/237/calendar.html?show_print_setup=1&locale=en-US

![image](https://cloud.githubusercontent.com/assets/1275831/8785504/b981c600-2eed-11e5-89db-0942321690cb.png)

It also has calendar integration

![image](https://cloud.githubusercontent.com/assets/1275831/8785518/cb596b76-2eed-11e5-8c6b-a5575e78a150.png)

**Comment by luqmaan** [comment]
Closing this issue since it seems most of the functionality is already implemented Recollect.

Feel free to reopen.
