### ISSUE TITLE
Setup Slackin to make Slack more accessible

### ISSUE THREAD

**Issue by luqmaan** [open-austin/project-ideas#19]
**Concise description**: 

Allow people to join open-austin.slack.com without the invitation nonsense.
**Link (more details/brain dump/alpha)**

See http://slack.refreshaustin.org/ for an example.

https://github.com/rauchg/slackin

**Project Needs (dev/design/resources)**

A developer to deploy it to the open austin server, or to Heroku.

**Status (in progress, pie-in-the-sky)**

~~Needs somebody to start this.~~

---------

## Completed thanks to @larcher!

Deployment instructions at https://openaustin.hackpad.com/Slackin-xqv0iwZexFF

**Comment by mateoclarke** [comment]
Yaz! this would help @amaliebarras by cutting out a manual task. But it would allow anyone without filter to join our Slack _(That is probably a good thing)_.

What's the cost structure for Slack? Any reason this could get out of hand in the long run?

**Comment by amaliebarras** [comment]
https://changeis.slack.com/pricing <https://changeis.slack.com/pricing>

This is the pricing structure of slack. 

10,000 messages are free, and if we want an unlimited archive it’s $7/month. I don’t think we’d ever qualify for the Plus or Enterprise plan.

Adding people to slack isn’t hard to do manually, but if we put a link on the website, this would allow us to connect on slack with people who didn’t come to a meetup or hack night. Which is a good growth move

I’m in total support of this!

**Comment by mateoclarke** [comment]
We're at around 5.4K messages according to the admin stats page. It sounds like only the last 10k message are searchable. Once we get past 10k, old message will be become pretty ephemeral. 
https://open-austin.slack.com/admin/stats

We have $50 credit _(not sure how)_ but it looks like it would cost us $7/user/month. Currently have 86 users. (over $7,000 per year if we needed to upgrade to the basic plan)

**Comment by amaliebarras** [comment]
ooooh it’s 7/month per user? I didn’t catch that.

how long did it take us to get to 5.4k?

**Comment by mateoclarke** [comment]
Dec 14th, 2014 is when we started using it.

**Comment by johntyree** [comment]
How important is it to log and search old messages for us, really?

If it is, but it's just archival we're concerned about then we can always log it ourselves. There's an IRC gateway that works great. I use it daily.

**Comment by mateoclarke** [comment]
@johntyree: I would say not that important. Important announcements and discussions should end up on the website or a github repo.

**Comment by johntyree** [comment]
I would agree. I think the 10k limit will be more than enough for the foreseeable future.

**Comment by luqmaan** [comment]
We now are on the Slack standard plan thanks to https://slack.zendesk.com/hc/en-us/articles/204368833-Slack-for-Nonprofits

**Comment by johntyree** [comment]
Nice. I notice on that page that it says we should let them know if we're going to grow beyond 100 members. We already have over 80. We should bring it up sooner rather than later.

**Comment by luqmaan** [comment]
Already did that

**Comment by johntyree** [comment]
:+1: :*

**Comment by larcher** [comment]
@luqmaan and I got this working on Heroku.  

Currently here: http://openaustin-slackin.herokuapp.com/

**Comment by mateoclarke** [comment]
Awesome!!!!! :fireworks: :fireworks: :fireworks: 

Thanks @larcher!

**Comment by luqmaan** [comment]
Nice work @larcher. I'll find out how to setup the slack.open-austin.org subdomain.

We should write deployment instructions somewhere. Maybe on hackpad? https://openaustin.hackpad.com/Slackin-xqv0iwZexFF

**Comment by luqmaan** [comment]
[slack.open-austin.org](http://slack.open-austin.org)
