### ISSUE TITLE
Setup Transitime for transit predictions

### ISSUE THREAD

**Issue by luqmaan** [open-austin/project-ideas#21]
**Concise description**: 

Setup [Transitime](http://transitime.org) to generate realtime transit predictions based on the position of the CapMetro vehicles.

**Link (more details/brain dump/alpha)**

Currently CapMetro does not provide a way to find out when the next bus is coming. They have internal API that can be queried to find out arrivals for one particular stop, but it is very limiting (and its internal, so...).

In an ideal world, CapMetro would publish a Trip Updates feed (which is a flat file containing estimated arrival times for every single stop). https://developers.google.com/transit/gtfs-realtime/

CapMetro uses Trapeze/ATIS, which isn't able to provide a GTFS-RT feed because it sucks. Also, CapMetro hasn't been able to find something to replace Trapeze/ATIS yet. So, lets take things into our own hands and generate these predictions ourselves.

Transitime is an open source Java project that does this. https://github.com/Transitime/core/wiki/Overview

**Who will use/benefit from this project?**

Users of [Instabus.org](http://instabus.org) will be able to find out when the next bus is coming more quickly. Instead of just showing the arrival time for one route+direction at a time, we can show the arrival times for all the routes and all the nearby stops at once!

**Project Needs (dev/design/resources)**

~~Java developers! Please! We don't know anything about Java and Transitime has very sparse documentation.~~  @walkeriniraq is HELPING with the Java-ing

Transitime is running: http://transitime-host.cloudapp.net/api/v1/key/f18a8240/agency/cap-metro/command/predictions?rs=801%7C5864

Next is to add a OneBusAway VM.

https://github.com/OneBusAway/onebusaway/wiki/Running-Onebusaway
Quickstart guide:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/OneBusAway-Quickstart-Guide

**Status (in progress, pie-in-the-sky)**

In progress, track progress here: https://github.com/luqmaan/Instabus/issues/210

**Comment by mjohnson290** [comment]
Hm, I may be down for this. I'll start reading up on documentation tonight. I've got some experience with Java, though I'm mostly a front end developer and have been using angular lately.

**Comment by mjohnson290** [comment]
Looks like they already publish real-time data here : http://www.capmetro.org/metrolabs/

**Comment by luqmaan** [comment]
Not quite. :kissing_smiling_eyes: 


There isn't a TripUpdates feed or an equivalent (public) API for providing arrival prediction times.

CapMetro just sent us their first TripUpdates file, but they still need to hook it up to Socrata.

Are you free tomorrow evening? I'll be at epoch coffee (n Lamar) working on this project.

**Comment by scrudden** [comment]
I have been working on making it easier to build and setup transiTime. Do you need some help?

**Comment by luqmaan** [comment]
@scrudden Thanks for reaching out to us! I'll contact you if we have any specific questions.

We've been posting updates here: https://github.com/luqmaan/Instabus/issues/210 and on http://slack.open-austin.org #transitime.

**Comment by djstroky** [comment]
Regarding your newly created onebusaway-docker, I'm interested in following and helping.  I don't have experience with docker, but recently made some EC2 deployment scripts for OBA over here: https://github.com/trilliumtransit/oba_rvtd_deployer  I'm not a guru with devops, so I'm interested to learn what things docker has to offer.

**Comment by werdnanoslen** [comment]
@luqmaan is see from luqmaan/Instabus#210 that this has been completed. Is this idea issue effectively done then?

**Comment by werdnanoslen** [comment]
This idea was delivered on. And to quote the source repo on the success: 

:warning: Instabus is deprecated.

Thank you for your support and for advocating to CapMetro the need for realtime transit data. Thanks to your help, CapMetro noticed Instabus and invited us to work with them to publish realtime data. CapMetro now publishes [reliable GTFS-realtime feeds](https://data.texas.gov/capital-metro), which means more than just the CapMetro app and Instabus can show realtime data for Austin.

Try out [Transit](https://transitapp.com/), possibly the best realtime transit app that works in Austin. For more transit apps  take a look at [awesome-transit](https://github.com/luqmaan/awesome-transit).

I'll close this issue now, since it's effectively finished and unrevivable. Congrats @luqmaan !
