### ISSUE TITLE
Scrape park photos for Austin Parks

### ISSUE THREAD

**Issue by prestonp** [open-austin/project-ideas#22]
**Concise description**: 

Scrape park photos for [Austin Green Map](https://github.com/open-austin/austingreenmap)

**Link (more details/brain dump/alpha)**

Brain dump, currently working on a scraping implementation in node.js. Planning on setting up a weekly cronjob to look at the park data and search Flickr for photos. The photos will be publicly available through github pages with an index file per park.

**Who will use/benefit from this project?**

The project will provide photos for Austin Green Map but others should be able to use it freely. I'm looking into sourcing creative commons photos.

**Project Needs (dev/design/resources)**

Right now I think I can put something together within a day or two.

**Status (in progress, pie-in-the-sky)**

In progress

**Comment by luqmaan** [comment]
Can you fill out the full project idea template? See the README https://github.com/open-austin/project-ideas

**Comment by prestonp** [comment]
Yeah, I completely forgot about the template, let me update

**Comment by decibel** [comment]
Is there code for this? A repo? (Disclosure: I'm not a web coder, so I doubt I could help on this...)

**Comment by prestonp** [comment]
@decibel I made a repo a while ago but I haven't gotten around to adding the photos to austin-green-map https://github.com/open-austin/austin-parks-photos

**Comment by amaliebarras** [comment]
Hey @prestonp what would it take to add the photos? What skills needed?

**Comment by amaliebarras** [comment]
Thanks for the update @prestonp !

**Comment by mscarey** [comment]
I don't think anyone else is going to want to try this strategy for enhancing Austin Green Map (AGM is itself inactive).
