### ISSUE TITLE
Open Data Progress Report -- need help coding!

### ISSUE THREAD

**Issue by haileypate** [open-austin/project-ideas#23]
**Concise description**
I work for the City of Austin (as of last week!) and we will be publishing a visualization on the City's website that displays open data participation for all the City departments. Our "minimum viable product" would be a basic HTML table, styled with CSS (and potentially some JS interactions), that more or less looks like the table that's provided in the Google Doc below. Ideally, the code would be embedded in a page on the City's Drupal website. We're open to ideas about how the presentation of the information could be enhanced to show a final score, ranking, filtering, search, etc.

**Link (more details/brain dump/alpha)**
The general layout that has been approved is demo'd here: https://docs.google.com/spreadsheets/d/1LNLJ_BXb7TOXFd1UXuNaHS-HwMvktr0-RrxGsLaVm7Q/edit?usp=sharing

**Who will use/benefit from this project?**
This visualization (if accepted) would be published on the City of Austin website. It would demonstrate which City departments have been participating as expected in Austin's Open Data Initiative.

**Project Needs (dev/design/resources)**
HTML/CSS/Javascript. We would present the visualization through the City's website, which utilizes the Drupal platform. The data that feeds the visualization will be hosted on the City's Socrata website, which is accessible by Socrata's SODA API. I am willing to work with developers to stage the data on the portal as needed.

**Status (in progress, pie-in-the-sky)**
The data has been staged with current progress as of Wed (Aug 5) at 5pm, and the dataset should be complete with all final 90-day statuses by next Monday (Aug 10). So far, we haven't started writing any code for the visualization. The final product would need to be accepted by City leadership, based on quality and feasibility. We want our departments who have participated in our Open Data Program to feel proud of their hard work and showcase their progress to the community!

Reach me here on GitHub or, better, at hailey.pate@austintexas.gov.

**Comment by luqmaan** [comment]
DataTables may be useful. https://www.datatables.net/

**Comment by mateoclarke** [comment]
Hey @haileypate, 

I'd like to start hacking on this. When will the data be available? Are you still thinking about using the SODA API to publish the data?

I think the best way to get started is to create a repo under open-austin. From there, you can fork code into the CTM repo, or just extract the HTML/CSS/JS needed within a Drupal module.

**Comment by luqmaan** [comment]
http://datasd.gitbooks.io/council_report/content/main/inventory_findings.html

**Comment by mscarey** [comment]
I'm going to speak up for the easy and ugly solution: simply put your data in the Google Doc and embed it on your site. You can always export CSV from Google Docs to put it on Socrata. Here's the code to embed a copy of the Google Doc where I added some minimal formatting and color-coded the fields:

```
<iframe width='600' height='600' frameborder='20' src="https://docs.google.com/spreadsheets/d/1jAZ1wIlYO1wBSRzOW1WVFeBSbLbtBkhe8b6-5dqfTsc/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false"></iframe>
```

And here's the link to the Google Doc itself, in case you want to make a copy and continue working in it:

https://docs.google.com/spreadsheets/d/1jAZ1wIlYO1wBSRzOW1WVFeBSbLbtBkhe8b6-5dqfTsc/edit?usp=sharing

Also, as as alternative to creating complex Javascript interactions in a new visualization made from scratch, you could try updating Austin's entry in the Open Knowledge Foundation City Open Data Census: http://us-city.census.okfn.org/

The Census is a very readable small-multiples visualization, and it's good for ranking cities against one another as well as ranking departments within a city (even though the categories of government function in the Census are more generic and won't exactly correspond to how Austin's departments are organized).

**Comment by haileypate** [comment]
@luqmaan Thanks for the link! We're looking at a few more measures than San Diego, but it would be off the chain if we could do something more interactive. Here's my favorite example, powered live portal data: http://datasf.org/progress/

@mscarey The OKFN census is one of my favorites! When I checked last month, the site was frozen for maintenance and we couldn't update... so thanks for the note... now that it's taking updates again, we'll have to knock that out. cc @mateoclarke 

@mateoclarke I'll put the numbers on the portal now.. please stand by!

**Comment by haileypate** [comment]
@mateoclarke Here's the data as of last Friday. I'll be updating it as departments continue to submit their work. https://data.austintexas.gov/Government/Open-Data-Initiative-Progress-Report-Participation/8qty-vat2/

**Comment by mateoclarke** [comment]
Sweet! I got a couple folks interested in working this week. @haileypate, any important deadlines or dates for this project?

**Comment by haileypate** [comment]
Well, yes and no. The Web Services team at CTM will present its findings to the Open Government (Commission/Committee/Governing Board/People?) on Wednesday, August 19... and plans for the next 90-day sprint to "Free the Data" will begin to form at that time. There is no firm deadline for publishing progress on the City's website, but we'd like to do it sooner rather than later. 

Let's say a prototype by Friday, 8/21 would be awesome. That way, we could pitch to the Web Services team during the week of Monday, Aug 24 for acceptance and approval of a proper publication timeline. I've looped in MattE and others about this project, but since I'm not on the ATX Drupal Dream Team myself :D, I need to huddle with the team and get a sense for what it would take to deploy an approved viz at austintexas.gov.

**Comment by mateoclarke** [comment]
Hey @haileypate, @sharlalikesyou and I put together a prototype progress report scoring card system. Check out what we have so far:

http://open-austin.github.io/open-data-progress-report/
https://github.com/open-austin/open-data-progress-report

**Comment by amaliebarras** [comment]
Ugh it doesn't work on mobile but I CANT WAIT TO SEE THIS!!!!!

**Comment by chip-rosenthal** [comment]
Excellent content. I'd suggest, however, the application may not be a good fit for a 2d/grid UX. A linear arrangement would make it easier for people to scan and compare entries.

The grid arrangement, for instance, doesn't give me a feel for how many "submit plan" entries are red. If it was linear I could scan the column and reach some conclusions.

**Comment by amaliebarras** [comment]
Okay, this is fantastic! I really like the fact that each department has their own scorecard, but they can also see what everyone else is up to too! Especially when there's lots of green. 

I noticed that he grid starts below the fold when I’m looking on a laptop which means the user has to scroll down to see the top part of the report card. It might be worth making the intro text at the top go a little wider so everything else shifts up?

Also let me know where this’ll be hosted, what URL and everything, I’ll create a Google Analytics account and give you guys a UA number to put in that script tag in the HTML

**Comment by mateoclarke** [comment]
@chip-rosenthal & @amaliebarras: I appreciate the feedback about the layout and mobile responsiveness. I'll work on an alternative layout over the weekend and make mobile work for the next iteration. 

Amalie, if you want to go ahead and create the Google Analytics ID, I can include it. This will continue to be hosted on Github Pages and it may be incorporated into the CoA Drupal site. That's up to @haileypate 's team...

**Comment by haileypate** [comment]
Wow, this is so great. I can't wait to show the team tomorrow! Great job @mateoclarke and @sharlalikesyou! 

Stuff I especially like: 
- The icons y'all chose for the 4 compliance items
- How easy it is to see which departments still have work to do
- How there's a statement at the top that says how many departments are counted

I'll put my additional questions and ideas in the project repo. I'm already so excited about where this could lead us next! Thank y'all so much!!

I'll go ahead and close this out since this seems to have transitioned from idea to project. Feel free to re-open if needed!

**Comment by mateoclarke** [comment]
To your suggestion @chip-rosenthal:
http://open-austin.github.io/open-data-progress-report/alt-version.html

Also included some of your "below the fold" feedback @amaliebarras

**Comment by amaliebarras** [comment]
Ooo yes, this looks wonderful and I like that the border shows up when the user hovers so it still kind of preserves the card feel.

**Comment by amaliebarras** [comment]
also @mateoclarke Here's the GA Number: UA-66672781-1. I have the default URL set to open-austin.github.io/open-data-progress-report/ for now. I'll add you, @haileypate, and @sharlalikesyou as GA users, let me know if I need to include anyone else

**Comment by chip-rosenthal** [comment]
Thanks for trying these. I find the alt format is far superior for data analysis. I'm able to scan and as a whole get a feel for where the city is and which tasks need to be done.

Another possibly interesting visualization is a thermometer graph ... something like a scale 0-8 ... give 1 point for each milestone started (currently showing yellow) and 2 points for complete (currently showing green). This might also be a good quantity for sorting, for looking at departments in a least-completed to most-completed fashion.

**Comment by mateoclarke** [comment]
Hey @chip-rosenthal, I like the thermometer idea, and had thought of something similar myself. 

Are you suggesting that as a separate graph? If so, what would that look like? 

Or do you see that as a 6th column? Or maybe just a background shade behind the department name and icon in the first column? 

I also like the idea of being able to sort by that metric.

**Comment by haileypate** [comment]
Just now seeing these... I like the thermometer idea too. How do y'all feel about migrating these to the issues area on the project repo?

**Comment by luqmaan** [comment]
:+1: for moving specific discussions to issues on the repo.

Lets keep this issue updated with the project status tho.

**Comment by haileypate** [comment]
Makes sense. Should we open this back up or leave it closed?

**Comment by luqmaan** [comment]
I would say keep it closed. The project has been launched and has momentum.
