### ISSUE TITLE
Create simple webapp to assist in measuring transitime accuracy

### ISSUE THREAD

**Issue by walkeriniraq** [open-austin/project-ideas#30]
App should:

- Record the bus and route you're on
- Every X seconds query our transitime instance for that bus and route and record the estimated time to the next stop.
- Every X seconds query CapMetro for the same information as above.
- Allow the user to note when they've reached the next stop (and which stop that is)
- Store this information in a database

The app should look like:

- List of routes
- Click a route
- List of stops
- Click on the stop you're closest to whenever you pass it

**Comment by walkeriniraq** [comment]
Suggestion is to build a node.js app.

**Comment by djstroky** [comment]
Perhaps you could slightly modify this node.js app I made:  https://github.com/djstroky/OnTransit

**Comment by luqmaan** [comment]
Here's what I'm thinking for the UI:

![image](https://cloud.githubusercontent.com/assets/1275831/10372576/094e599c-6dae-11e5-9157-e39260f9e8dc.png)

**Comment by luqmaan** [comment]
We could also save a bunch of work and just sneak this into Instabus by adding an arrive button to the stop popup.

![image](https://cloud.githubusercontent.com/assets/1275831/10372596/27629f6a-6dae-11e5-9de3-084b30e382d9.png)

**Comment by luqmaan** [comment]
![image](https://cloud.githubusercontent.com/assets/1275831/10373409/d8409aea-6db2-11e5-8854-b2ca9b14b72e.png)

**Comment by luqmaan** [comment]
I just rode the 803 to Rosedale station, and CapMetro's prediction arrival time prediction was mostly correct. The Transitime prediction said the bus would arrive in 2 minutes even when it had already arrived.

In terms of this webapp, I think this is the data we need to store for each stop:

- stop id
- route id
- trip id
- direction id
- actual time of arrival
- capmetro prediction: 3 minutes after arrival, 2 minutes after arrival, 1 minute after arrival, 30 seconds after arrival, 15 seconds after arrival, at arrival time, 15 seconds before, 30 seconds before, 1 minute before, 2 minutes before, 3 minutes before, 5 minutes before, 10 minutes before, 15 minutes before, 20 minutes before, 25 minutes before, 30 minutes before
- transitime prediction: 3 minutes after arrival, 2 minutes after arrival, 1 minute after arrival, 30 seconds after arrival, 15 seconds after arrival, at arrival time, 15 seconds before, 30 seconds before, 1 minute before, 2 minutes before, 3 minutes before, 5 minutes before, 10 minutes before, 15 minutes before, 20 minutes before, 25 minutes before, 30 minutes before

**Comment by luqmaan** [comment]
I've added transitime predictions to Instabus. https://github.com/luqmaan/Instabus/pull/217

As far as measuring accuracy, it looks like Transitime has some reporting built into the webapp.

See the conversation on #transitime slack for more info.

![image](https://cloud.githubusercontent.com/assets/1275831/10865320/a9d35e06-7fd5-11e5-8ae0-4f373e8d4910.png)
![image](https://cloud.githubusercontent.com/assets/1275831/10865324/ac3e6e24-7fd5-11e5-9eeb-7dab3c0a9444.png)
