### ISSUE TITLE
Asian-American Quality of Life / Community Engagement (doing it better)

### ISSUE THREAD

**Issue by CPIOBenAdams** [open-austin/project-ideas#31]
**Concise description**: 
What does quality of life mean to you? A new initiative approved by the Mayor and City Council seeks to improve services and programs for Asian Americans in Austin. First, it is paramount to reach out to and hear from Austin's diverse Asian community. With your help, we'd like to create a web app or simple online platform making it easy for residents to engage with the project.

**Link (more details/brain dump/alpha)**

**Who will use/benefit from this project?**
Austin's Asian-American population. 

**Project Needs (dev/design/resources)**
Your brain. Strategy about the user experience and development of a web interface. We have mocked up some concepts as a starting point, and open to iterate and make better with your insights.

**Status (in progress, pie-in-the-sky)**
This project is underway. The City of Austin will definitely be implementing this project. Learn more at www.austintexas.gov/asianlifeaustin.

**Comment by luqmaan** [comment]
> a mobile app that would allow some participants to engage in this activity from the comfort of their homes and without the assistance of a City of Austin facilitator

> a mobile app that would incorporate the themes, game/artistic concept, survey, and informational materials into its user interface

Those are a lot of things for a mobile app. Is there any specific part that you think is the most essential?

- game
- survey
- informational material

**Comment by Marion3Sanchez** [comment]
Thank you for the meeting! You guys are AwEsOmE!

**Comment by VictoriaODell** [comment]
A couple of questions: 
1. Did the last 2 initiatives have a digital application/site or anything to accompnay them? 
2.  How long do the initiaves live?

**Comment by Marion3Sanchez** [comment]
1. The African American and Latino/Hispanic Quality of Live did not have a digital application. It was primarily face-to-face and paper surveys. We are having those elements as well, but wanted to have a digital engagement piece as well.
2. The initiative will live for a long time. The African American has been in placed for about 10 years and the Hispanic/Latino for about a couple of years. For the Asian American one, we are in the research phase. This phase will last about 8 more months.

Thank you for your interest!

Marion

**Comment by whgest** [comment]
Mentioned this to a couple people, but I worked with the city last year to make a simple mobile survey app, visible at http://www.budgetboxapp.com/welcome.


It's configurable, supports multiple languages and device types (good ol' bootstrap) and can update a socrata database. 

Simple and basic (just me and one designer worked on it), but proven and tested. Might be useful as a foundation for a project like this. If not, I can help scope this project or share the challenges we had with it. 

Code here: https://github.com/whgest/budgetbox

It's an ember.js application with a very simple node authentication layer. Deploys to heroku.

**Comment by Marion3Sanchez** [comment]
Thank you for the comment. Jill Goodman presented at the meeting and we got some very important feedback which we took into consideration. The engagement tool is now called "Conversations Over Tea," and we are providing a variety of teas and a beautiful mug for the host. What we were trying to do is to have an app for community members that wanted to provide the feedback. Your groups recommended just to do a survey monkey kind of design. I am in the process of designing all the research instruments.We are deploying Jan 20 with our first guided conversation.

**Comment by whgest** [comment]
Simple is good. Good luck with the project!

**Comment by amaliebarras** [comment]
@Marion3Sanchez Hi there! I know it's been a while, but I'm wondering where this project went and what the status currently is.

**Comment by Marion3Sanchez** [comment]
@amaliebarras much has happened! We did the Conversations Over Tea, got over 3000 comments, 2500 + 850 surveys filled out and many community meetings. If you like data, is all here: 
https://data.austintexas.gov/Government/AAQOL-Survey-Monkey-Answers-Nov7-Update/i3d7-gc2g 
https://data.austintexas.gov/Government/AAQOL-Community-Comments-Oct-27-2016/75gm-hb4x 
https://asianlifeatx.bloomfire.com/?feed=recent 
http://austintexas.gov/department/documents-3 

Thank you for checking in!

Marion

**Comment by amaliebarras** [comment]
@Marion3Sanchez I saw your presentation last week in the citywide lightning talks after writing my comment. Congrats on the activity! 

We do love data! Is there any need for Open Austin help on this project? And if so, is there a public link where we can point potential collaborators?

**Comment by Marion3Sanchez** [comment]
So cool! Let's visit! I would love to support in any kind of project! Have you seen the data links?

**Comment by werdnanoslen** [comment]
@Marion3Sanchez we'd love for you to come to our next hack night! https://www.meetup.com/Open-Austin/
Can you join us?

**Comment by Marion3Sanchez** [comment]
@werdnanoslen when is your next meeting? and what role would you like me to play at it?

**Comment by werdnanoslen** [comment]
Hi @Marion3Sanchez, sorry I never responded to your question. We have a hack night coming up this week! https://www.meetup.com/Open-Austin/. You can also subscribe to updates or check our Slack announcement channel for new ones.

How is this project going? Has the city deployed it?

**Comment by mscarey** [comment]
This was related to a city initiative that I think is now done. It's not easy to sync an Open Austin project with a city program, and it really didn't happen here.

**Comment by Marion3Sanchez** [comment]
The AAQOL Initiative is an Action Research type of project with a core question to compare the QOL of others with the Asian Americans in Austin. A report has been presented to council, the AAQOL commission and a variety of communities. You can access the reports here http://austintexas.gov/department/documents-3 . Additionally, the commission meets at least once per month to discuss strategies and budget recommendations to improve the QOL of Asian Americans in Austin.
