### ISSUE TITLE
Policy Campaign - "Open by Default"

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/project-ideas#33]
### Repo for this Project Idea Lives [here](https://github.com/open-austin/open-by-default). If you'd like to contribute, please take a look at the open [issues](https://github.com/open-austin/open-by-default/issues)

**Concise description**: 
_(I'm trying something new. I want to draft a policy document using Github. This is a transparent and collaborative system we can use to craft and polish our policy statements.)_ 

Open Austin believes 21st century governance can work for the people. We build open source technology and organize volunteers to envision government services made more simple, effective, and accessible. We also advocate for policy reform that frees government data and opens up technology procurement, budgeting, and development and the local level.

Using a [template](https://github.com/open-austin/open_by_default/blob/master/template.md) from a previous [Community Technology & Telecommunications Commission](http://austintexas.gov/cttc) action, I want to draft a policy statement that encompasses some goals and policy changes we'd like to see adopted related to Open Data.

As a starting point, [Asheville, NC](http://www.codeforasheville.org/open-by-default-recommended-provisions/), has a good outline of ideals I've edited slightly for Austin:
https://github.com/open-austin/open_by_default/blob/master/README.md

Steps:
1. Draft formal policy recommendation
2. Stand up a single page site with basic content on the issue.
3. [profit?](http://cdn.niketalk.com/1/1f/1f9024f2_underpants-gnomes.jpeg)
4. Draft a blog post to be shared via open-austin.org on the importance and potential impact an open by default policy.
5. Advocate for Economic Opportunity Subcommittee draft and discussion of a resolution
6. Meet with staff from CMs Troxclair, Casar, Pool, and Houston who all sit on [Economic Opportunity Subcommittee](https://www.austintexas.gov/department/economic-opportunity-committee)
7. Ask organizations (like Capital Factory, KUT, Austin Monitor, Prof Royal at Texas State, Business Councils etc) to formally support a recommendation once adopted by CTTC and sent to City Council Subcommittee on Economic Opportunities. 
8. [world domination?](http://cdn.meme.am/instances/500x/59895613.jpg)

**Link (more details/brain dump/alpha)**
More news and relevant articles on recent FOIA and Open Data issues in Austin:
http://www.mystatesman.com/news/news/local/open-records-squabble-blooms-overs-austin-music-ce/nnwFd/
http://kut.org/post/public-information-requests-rely-honor-system-austin-city-hall
http://kut.org/post/uber-sues-city-austin-and-state-attorney-general-block-data-releases
http://www.routefifty.com/2015/07/los-angeles-ron-galperin-controller-open-data/116935/

Also, good idea for the newer folks to skim through some policy content we've worked on in the past.
http://www.open-austin.org/policy

**Who will use/benefit from this project?**
Consumers of open data. Journalists who write stories. Academics who do research. City of Austin internal departments who can analyze and join their data with other department data for more robust insights. Council Members who will be able to make data-driven decisions on City Policy. Citizens who can most actively make change in their neighborhoods. Developers who can build apps and web services with data to tell a story and drive actions.

**Project Needs (dev/design/resources)**
Policy wonks and language nerds

**Status (in progress, pie-in-the-sky)**
Experiment

**Comment by spatialaustin** [comment]
yes! related, and possibly as a supplement, i would love to see a running list of datasets the community wants open.

**Comment by mateoclarke** [comment]
@spatialaustin: I made this for you. :sun_with_face:  
https://github.com/open-austin/liberate-the-data

**Comment by werdnanoslen** [comment]
@mateoclarke what's the status on this?

**Comment by werdnanoslen** [comment]
From @mateoclarke:

> We were collecting a list of datasets the community wants suggested to be published:
> https://github.com/open-austin/liberate-the-data/issues
> 
> the repo basically serves as documentation: https://github.com/open-austin/open-by-default
> and a lot of what we brainstormed in here ending up in the 2016 policy priorities doc
