### ISSUE TITLE
Boilerplate for static pages

### ISSUE THREAD

**Issue by prestonp** [open-austin/project-ideas#35]
**Concise description**: 

Create a boilerplate project to create static page applications similar to [austingreenmap](https://github.com/open-austin/austingreenmap) or [austin-park-equity](https://github.com/open-austin/austin-park-equity). This would be highly sporkable and easily deployed to github pages. 

**Link (more details/brain dump/alpha)**

The front end tooling ecosystem changes a lot, but it would be a huge help for people to get started right away.

Personally, I would like
- es6
- common js
- concatenation/minification
- sass
- deploy to gh-pages
- unlicense

Then others can pick a JS framework or do it vanilla.

**Who will use/benefit from this project?**

Devs at hack nights that are starting new projects and don't want to spend an hour setting up a gulpfile, browserify, webpack or what-have-you

**Project Needs (dev/design/resources)**
Devs

**Status (in progress, pie-in-the-sky)**
pie

**Comment by avidas** [comment]
:+1:

**Comment by amaliebarras** [comment]
Does [this guy](https://github.com/werdnanoslen/mobile-map-io) accomplish the things that this idea suggested?

**Comment by prestonp** [comment]
@amaliebarras That project creates a webserver that talks to a mysql db. It looks neat but setting up a webserver, db and hosting them is somewhat heavy for a hacknight.

https://github.com/facebookincubator/create-react-app is a great boilerplate project that makes hacking really easy. You can use this to build a static website and stick it on github pages. But it's for react, which not everyone uses/likes/cares for.

IMO this issue is too broad. The front end world changes wayyyy too fast. I'd recommend folks just look up boilerplate projects with their fav technologies.

**Comment by amaliebarras** [comment]
ah okay @prestonp ! I didn't realize that about the mobile boilerplate.

that create-react-app thing looks neat at first glance. is it beginner friendly or do you have to know react for it to be useful? 

maaaaan why can't we just have a "make app" button!? haha actually I came across [this tool](http://gomix.me) recently and I think that's what they're trying to do. breaks a lot though 😢  not super stable (yet!)

**Comment by VictoriaODell** [comment]
Closing this since " I'd recommend folks just look up boilerplate projects with their fav technologies".
