### ISSUE TITLE
Help for Austin Vets

### ISSUE THREAD

**Issue by ss2k** [open-austin/project-ideas#38]
We should have a site that helps match jobs / training programs to veterans living in Austin. We could match what they did in the military and help them transition to a civilian job.

**Comment by mateoclarke** [comment]
Hi @ss2k! Can you update your comment using this template? We'd love for you to elaborate on your idea.

https://github.com/open-austin/project-ideas#template-for-new-project-ideas

**Comment by VictoriaODell** [comment]
Closing this because of lack of information.
