### ISSUE TITLE
Icon Set: Open Austin 

### ISSUE THREAD

**Issue by betsydupuis** [open-austin/project-ideas#39]
**Concise description. What problem are you trying to solve?**: 
Looking across projects, I've noticed a number of projects that have similar icons that are specific to Open Austin / Civic minded projects.

It would useful to have a set of icons for bootstraping projects quickly. It would also promote a layer of design consistency.

**Link (more details/brain dump/alpha)**

**Who will use/benefit from this project?**
Open Austin designers and developers

**Project Needs (dev/design/resources)**
- A list of desired icons
- An artboard template for icon alignment and documentation
- Styleguide? 

**Status (in progress, pie-in-the-sky)**
I've implemented this kind of project before in SVG, so it's feasible.

There are also many icons already in use across projects.

**Comment by luqmaan** [comment]
I think this project idea solves a problem that we face and I'm sure many other brigades face. Maybe we could even release this work through CfA like Code for Hawaii did with https://github.com/codeforamerica/awesome-civic.

> A list of desired icons

We've needed plenty of icons for Austin Green Map.

- Some are from maki: https://www.mapbox.com/maki/
- Some are from the noun project: https://github.com/open-austin/austingreenmap/issues/13#issuecomment-117161246

**Comment by luqmaan** [comment]
I've opened a PR to add an icons section to the awesome-civic list. https://github.com/codeforamerica/awesome-civic/pull/13

@betsydupuis Do you have any icon sets that could be added?

**Comment by betsydupuis** [comment]
@luqmaan I have done some work on designing a consistent set and have created a build process. 

I can totally design some icons.

I think we need these steps:
**V1**
1) Create layout templates (this is important for reasons)
2) Create a build process
3) Write base CSS for the icons
4) Write docs.
5) Add existing icons

**V2**
1) Write / Design a styleguide
2) Redesign the set to be internally consistent
3) Accept contributions
 
*V3*
1) Create subsets of icons when things get too big

**Comment by betsydupuis** [comment]
I created an example build system.
https://github.com/betsydupuis/svg-icon-sprite

Next I'm work on documentation for aligning the icons against the typographic baseline. 

It's not an exact science because of variations in fonts and browsers. Previous work I've done on icons has been more controlled because we were working against the styleguide for a particular brand using a particular font.

Here's my existing example:
<img width="939" alt="screen shot 2015-11-30 at 3 29 27 pm" src="https://cloud.githubusercontent.com/assets/2096627/11485031/2e512614-9777-11e5-9fad-45f579860cbd.png">

It might be easier to just default to the Material design guidlines, but it is probably too detailed a guideline for our MVP.
https://www.google.com/design/spec/style/icons.html#icons-system-icons

**Comment by VictoriaODell** [comment]
Closing this because of lack of movement. I hope you're well @betsydupuis
