### ISSUE TITLE
hackpad embed module

### ISSUE THREAD

**Issue by chip-rosenthal** [open-austin/project-ideas#4]
**One sentence description**

A module that can be embedded in the www.open-austin.org website that highlights recent hackpad activity.

**More details/brain dump/alpha:**

The Open Austin Hack Team keeps information at https://openaustin.hackpad.com/

It would be helpful to have some module that can be embedded into the website to highlight pads with recent activity.

Hackpad does have an API that may be suitable for this purpose.

Likely implementation would either be a Word Press plug-in (PHP) or client-side Javascript.

**Project Needs (dev/design/resources):**

Initial need is research and scoping, to produce a design proposal.

Need to scope out the Hackpad API and determine feasibility/capability.

Need to assess whether this should be implemented server-side or client-side.

**Status (in progress, pie-in-the-sky):**

Concept idea.

There is a website redesign being considered, that it would be helpful to coordinate with that effort. It's being discussed in the #website channel on the Slack site.

**Comment by luqmaan** [comment]
For an embedded Javascript thing we need CORS or a proxy.

It looks like Hackpad is working on supporting CORS https://hackpad.com/Hackpad-API-bugs-xVJvm6lxNL1#:h=-CORS

**Comment by luqmaan** [comment]
Looks like List Updated Pads is an admin only API:


> **List Updated Pads (Domain Admins Only)**
Request: GET /api/1.0/edited-since/{timestamp}
Path Elements:
timestamp: Number of seconds since midnight Jan 1, 1970
Response:
JSON array of pad IDs. Only the oldest 1000 pads are returned.
`["C0E68BD495E9","653AF8F23731","485CF7D83139","73B503942C26"]`

**Comment by chip-rosenthal** [comment]
I hate the modern "let's ignore precedent and invent everything new" web development. This would be trivial if they provided an RSS feed.

I think the best bet may be to scrape. The content is marked up well enough to make this reasonable.

**Comment by luqmaan** [comment]
Haha yes, even worse is that dumb rss logo on every page that isn't actually rss.

**Comment by luqmaan** [comment]
Yeah either scraping the homepage or using their API from a wordpress plugin (ohboy) are the only viable options.

For the scraper:

- GET https://openaustin.hackpad.com/ with cookie `padlistSection=home` instead of `padlistSection=stream`
- Store the results somewhere accessible via cors/jsonp
- Setup a cron job

For a wordpress plugin via their API:

- Choose somebody's client/secret from hackpad the settings panel
- Use OAuth https://gist.github.com/deviantintegral/5488802
- Get the recently updated pads `/edited-since/{timestamp}` 
- Get metadata for each pad
  - `/pad/{padId}/content[/{revision}].{format}` 
  - Or alternatively just go to the pad html url and scrape the facebook open graph tags
  
    ```json
    "title": "Welcome (Read this 1st)",
    "description": "Ever been to a Civic Hack Night? Interested in our projects? Open Austin uses Hackpad to keep notes at it's meetups and to share links about projects, events, and initiatives. With a hackpad account, you can log in and update pages.",
    "image": "https://hackpad.com/static/img/hackpad-logo-112.png",
    "url": "https://openaustin.hackpad.com/Welcome-Read-this-1st-VdaDZFttRYX",
    "type": "hackpad:pad"
    ```

**Comment by mateoclarke** [comment]
I've enjoyed using Hackpad but if the lack of integration is a deal breaker I don't think we are so invested in it that it would be hard for us to migrate to something that plugs into Wordpress or has embeds as a core feature. 

And I don't think there is so much content posted on Hackpad that it requires a scrape. There are maybe 20 pads? 

So it seems to me that we should investigate if there is something comparable to Hackpad. Then decide if we should migrate our content from Hackpad or go with one of Luqmaan's two solutions on integrating Hackpad with Wordpress. 

I also think it'd be sufficient to just link to our Hackpad from the website. Deep integration with other services wasn't what I was thinking about when I started using it. And Hackpad has served its purpose very well until this question of deeper integration was brought into question.

**Comment by chip-rosenthal** [comment]
```ruby
require 'open-uri'
require 'nokogiri'
URL = "https://openaustin.hackpad.com"
doc = Nokogiri::HTML(open(URL))

puts("<ul>\n")
doc.css("div.segment-outer-wrapper").slice(0,5).map do |node|
  title = node.css("span.title-link").first.content
  href = URL + node.css("div.title").css("a").attribute("href").content
  lastEdited = node.css("div.segment-last-edited-date").first.content.strip
  printf "<li><a href=\"%s\">%s</a> (%s)</li>\n", href, title, lastEdited
end
puts("</ul>\n")
```

**Comment by luqmaan** [comment]
:+1: 

FYI, Hackpad is open source now that they've been acquired by Dropbox.

https://hackpad.com/Hackpad-is-teaming-up-with-Dropbox-m1Fne5A6Lzn
https://github.com/dropbox/hackpad
https://news.ycombinator.com/item?id=10099602

**Comment by VictoriaODell** [comment]
Closing this issue since we no longer use hackpad.
