### ISSUE TITLE
Fix Austin OpenDataCache

### ISSUE THREAD

**Issue by luqmaan** [open-austin/project-ideas#40]
**Concise description. What problem are you trying to solve?**: 

All the data on http://www.opendatacache.com/data.austintexas.gov/ looks like it stopped updating 5 months ago.

**Link (more details/brain dump/alpha)**

http://www.opendatacache.com/data.austintexas.gov/

**Who will use/benefit from this project?**

Right now nobody specific. But in general users of data.austintexas.gov that need faster responses.

**Project Needs (dev/design/resources)**

A developer needs to look into how OpenDataCache works and figure out the steps to get the data updated.

**Status (experiment, alpha, beta, official)**

Experiment

**Comment by VictoriaODell** [comment]
The links for this seem to be broken. Closing for now. If it's still an issue we should open a new issue.
