### ISSUE TITLE
Help Reduce Run off for New Development

### ISSUE THREAD

**Issue by ericwg** [open-austin/project-ideas#41]
Hey everyone.  I could use some help working on a policy item to help reduce flooding in Austin.  I'm with [AURA](http://www.aura-atx.org), and we're a grassroots urbanist group working for abundant housing and an Austin for everyone:

Short version:  The City is rewriting it's land development code (LDC) in a big project called CodeNEXT.  We're hoping that CodeNEXT can help solve a lot of problems in Austin, including providing more housing, improve the city to allow better public transportation, and, for this project: add more green infrastructure to help deal with specific problems in Austin.  We need analyzing rainfall data from [LCRA](http://hydromet.lcra.org/chronhist.aspx) to help inform a policy proposal.

Long version:  LCRA provides rainfall data every few minutes, which lets us determine how much rain falls every few minutes at areas around Austin.  Using this data, we should be able to determine how much rain falls over an hourlong period.  With a big enough dataset, that could help us learn how to build a performance standard for new infrastructure.  For example, let's say that the data showed that 90% of rainfall was less than 2 inches in one hour.  The performance standard could suggest that if onsite infrastructure at a new development (retaining ponds, berms and swales, cisterns, rainwater harvesting, evapotranspiration, etc) can retain that much water, then it could reduce the water contributing to floods in the area.  This would allow us to improve the flooding situation sometimes associated with new development and allow smart engineers and landscape architects figure out how to creatively solve problems.

What we need is to be able to present this data in a usable way to policymakers, engineers, and landscape architects.  One way that we're thinking is to break the rainfall data into percentiles over one or two hours.  So for example,  80% of storms had less than X inches of rain over two hours.  
![image](https://cloud.githubusercontent.com/assets/16139469/11569213/49fd6a9e-99b6-11e5-8a48-8c685028d946.png)

**Comment by davemcphee** [comment]
Here's a repo of the data being used: https://github.com/davemcphee/LCRARainFallanalysis
(I'm Alex S. btw)

**Comment by luqmaan** [comment]
Thanks dave

**Comment by amaliebarras** [comment]
Hey @ericwg ! I'm tagging some of our project ideas with the status, topics, and skills required. Is this idea something you'd still like to see, and are you able to be the point of contact?

**Comment by ericwg** [comment]
yes, this would be very useful as part of CodeNEXT.

**Comment by mscarey** [comment]
I feel like it's not explained how the amateur analysis within the scope of this project would support the efforts of environmental scientists and engineers. And the CodeNEXT connection makes it seem out of date. I think I'll close this but also check to see whether the #policy channel wants to reopen it.
