### ISSUE TITLE
Tool for finding business that don't allow "open carry" of handguns

### ISSUE THREAD

**Issue by TeknoFiend** [open-austin/project-ideas#43]
#### Concise description. What problem are you trying to solve?:

Would be nice to have a tool (API + site or mobile app) for keeping track of which businesses don't allow handguns to be carried openly. 

I think the API is pretty important as a standalone piece to allow other services can use the same data and do something interesting with it.

For the site or mobile app we'd want to at least support simple searching by business name and type. So a user could ask "Is HEB gun-free?" or "What pizza places are gun-free?".
#### Link (more details/brain dump/alpha)

All that's required of businesses is that they post a "30.07 sign" (http://momsdemandaction.org/campaigns/signage-rules-for-small-business-owners/) so we'd need to rely on crowdsourcing but there are already a few lists started to bootstrap from:
- http://momsdemandaction.org/campaigns/texas-businesses-say-no-to-open-carry/
- http://dining.blog.austin360.com/2016/01/04/list-of-austin-restaurants-opting-out-of-open-carry/
- https://gunfreebusinesses.wordpress.com/

We could also track the other gun preferences of business (e.g. prohibition of concealed handguns).

If the business does not post the "30.07 sign" they can put up a sign of their own design. If someone comes in with a handgun the business can tell the person that weapons aren't allowed and they must legally leave. So we'd want to qualify the data accordingly.

Because this is a very political issue we will need a way to allow users to help audit the information to mitigate intentional poisoning of the data.
#### Who will use/benefit from this project?

Initially just Austin area consumers. Maybe stretching out to all of Texas or even national level.
#### Project Needs (dev/design/resources)

Any help would be useful. Just an idea right now.
#### Status (experiment, alpha, beta, official)

Experiment

**Comment by VictoriaODell** [comment]
Hey, this is a cool idea. I have a few friends that are pretty anxious about open carry too. Also, don't forget to use the template for new project ideas(below).

**Concise description. What problem are you trying to solve?**: 

**Link (more details/brain dump/alpha)**

**Who will use/benefit from this project?**

**Project Needs (dev/design/resources)**

**Status (experiment, alpha, beta, official)**

**Comment by TeknoFiend** [comment]
Great, thanks!

**Comment by Srickshaw** [comment]
I'd be interested in helping out on this project - it sounds like a really important thing to have.

**Comment by mateoclarke** [comment]
Just found a new list of private universities' gun policies: http://apps.texastribune.org/private-university-campus-carry/

**Comment by afkamalipour** [comment]
Count me in for being interested in helping with this app.

**Comment by mmdotz** [comment]
I'm interested in helping with this. Will anyone be working on this at the Civic Hack today at the library?

**Comment by luqmaan** [comment]
@mmdotz FYI, the civic hack is at Urban Co-Lab not the library. http://www.meetup.com/Open-Austin/events/228334157/

**Comment by twomice** [comment]
Some prior art for consideration: https://www.texas3006.com/ (originally for 30.06 concealed-carry prohibition, but now including 30.07 for open-carry). I believe there are one or two mobile apps that aim to track this as well.

I'll also note that this tool would be useful and interesting for licensed handgun carriers as well as those who wish to avoid them.

**Comment by mateoclarke** [comment]
Sketch City, the brigade in Houston has some Open Carry [project ideas)](https://docs.google.com/document/d/1kgVd1nvWPxJPAf4DueqTQ2nhRIHry7J4JGat43klQW0/edit) listed for their May 14 hackathon. Maybe there is a collaboration opportunity there. 

One team could build an API, another could build some client side interfaces. Or even collaborate on both sides of the stack. What can we do to help get the ball rolling? Is there a Github repo started yet? Should we start an Open Austin repo? Either @luqmaan or I can help with that. @TeknoFiend, did you have a stack in mind for the API side? I saw the [.json directory](https://github.com/TeknoFiend/open-carry-directory/blob/master/directory.json) you started.

**Comment by fileunderjeff** [comment]
Here in Houston, we're partnering with Moms Demand Action who are putting together the open carry dataset. http://momsdemandaction.org 

We should collaborate!

**Comment by fileunderjeff** [comment]
@mateoclarke thanks for the shoutout! it would be super awesome to collaborate on this and other projects.

**Comment by fileunderjeff** [comment]
Here is an unofficial dataset from the Houston area: https://docs.google.com/spreadsheets/d/1h9sHI_HXr9AAKTkYXTi7BOLSeEKE4qieyaDyY3Jx5dw/edit#gid=0

**Comment by mateoclarke** [comment]
http://meganvo.github.io/opencarryaustin/

**Comment by fileunderjeff** [comment]
This is awesome!

Jeff Reichman
January Advisors <http://www.januaryadvisors.com/>
713.893.7930 . 832.477.7189 (m)
my story <http://linkd.in/QL0GW8> . @fileunderjeff
<http://www.twitter.com/@fileunderjeff>

**Comment by dheerajchand** [comment]
Defo interested in assisting on this!

**Comment by mmdotz** [comment]
I'm a Rails person - junior and would really like to help if you think
there is a need.

**Comment by TeknoFiend** [comment]
Hey guys. Glad there's so much interest in this (and related) projects. Unfortunately life is getting in the way at the moment and I won't have time to work on it. Someone want to volunteer to take over the reins?

**Comment by mateoclarke** [comment]
@mmdotz and I talked about this project tonight at Civic Hack Night and created a repo to get started.
https://github.com/open-austin/open-carry/

We both have experience with Ruby on Rails so we're going to start with a Rails API. :gem:  :steam_locomotive: 

I'm more front end focused and Michelle is admittedly a jr rails dev, so if anyone has tips for designing a Rails API or wants to dig in with us, just start adding issues and sending PRs.

**Comment by Ahelsinger** [comment]
Hey, y'all! Looks like I'm jumping in a little late here. I just saw this in 
Luqmaan's email. 

It's awesome that there's so much enthusiasm behind this. My company has an app that has a feature that shows gun permit information. http://www.spiritstexas.com/

We're launching an update for the app with some additional functionality soon.

**Comment by werdnanoslen** [comment]
Since this now has a project repo, I think we can close it as an idea now, right? Policy question for @amaliebarras @hlupico, but @TeknoFiend do you see value in keeping this open as a project idea, too?
