### ISSUE TITLE
Freecycle for Food

### ISSUE THREAD

**Issue by ataetemadi** [open-austin/project-ideas#44]
**Concise description. What problem are you trying to solve?**

Get unwanted food to people who want it.

**Link (more details/brain dump/alpha)**

> "More than 1 in 4 children in Texas are living in households that struggle against hunger." (http://tx.nokidhungry.org/hunger-texas). 

I regularly throw out all sorts of perfectly good food from my freezer or from my pantry where I didn't like it or I took so long to do anything with it that it expired. I wanted to do something about this ridiculous hunger epidemic in one of the richest states in one of the richest countries in the world so I started looking and there are a few places you can donate money but they don't tell you where the money goes or how much of it actually gets to people in need and if it made any difference. I want to develop an site/app like Freecycle but for food. The difference is someone comes and collects the food you don't like or need or is about to expire or you won't eat and take it and distribute it to people who want it. To start with it would be canned goods and dry food but later I have an idea to expand it to any kind of food even half eaten sandwiches etc.

**Who will use/benefit from this project?**

In particular, families struggling with hunger. Hopefully, everyone, because your own health depends on others being healthy too. 

**Project Needs (dev/design/resources)**

A designer to design the site and app. A developer to help me create the app. Anyone else willing to help administer or provide transportation or storage etc.

**Status (experiment, alpha, beta, official)**

Experiment

**Comment by mscarey** [comment]
You might want to look at keepaustinfed.org (@keepaustinfed on Twitter). They have a similar goal and I think they developed some of their software at a Code for America event a few years back. I think they had some regulatory issues preventing spur-of-the-moment donations. They may be able to benefit from more app/website work though.

**Comment by ataetemadi** [comment]
Thanks! I will contact them and offer my help. They do have a similar goal, but of course it is not the same idea.

**Comment by mateoclarke** [comment]
Another open source project to be aware of is this Food Rescue App built with Ruby on Rails for Vermont. http://datalook.io/food-rescue-vermont/

**Comment by VictoriaODell** [comment]
Sorry about the label thing above, I was trying to see what that label said.

**Comment by amaliebarras** [comment]
I have some buddies interested in forking the food rescue project! My pal Dustin (compost pedallers) was telling me he started a meetup group to solve this problem, and I remembered this thread. Making a mental note of the project ideas repo win! 

⚡️ 💡 ⚡️

**Comment by ataetemadi** [comment]
Hi Amalie,
I would love to be involved.  Please do let them know I am here to assist in any way I can.
Kind regards 
Ata 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by amaliebarras** [comment]
@ataetemadi I'd like to forward you an email with some information about this meetup group! That way you can plug in there and bring this idea to a group already working on it. Will you send your email address to amaliebarras (at) gmail . com?

**Comment by VictoriaODell** [comment]
Just want to follow up with some info that was sent from Austin Eco Network that is relevant to this. 

> [Food/Zero Waste] In Travis County (where Austin is located) 18 percent of the population and 25 percent of the children are food insecure. This means that they don't know where their next meal will come from. Meanwhile, 194.5 million pounds of food (worth more than $208 million) is wasted annually in this city.
> 
> So how do we fix this imbalance? A new group of activists are hoping to create a solution. The Save The Food Coalition is working to create a new city ordinance that will require restaurants and businesses to donate or sell their leftover (but still edible food), instead of just throwing it away or composting it.
> 
> Save The Food Coalition is trying to pass a new ordinance in Austin.
> 
> But wait, isn't this already happening?
> Our city already has a policy that requires food-related business to divert organic waste from the landfill. They can do this in a number of ways, including by donating food, composting, and simply reducing the amount of waste produced in the first place. This is a part of the Universal Recycling Ordinance, which has been popular within the environmental community, but as the Save The Food Coalition sees it, there are even more opportunities to serve the community and reduce waste at the same time. 
> 
> In a Facebook Live interview with the Austin EcoNetwork earlier this week, Save The Food Coalition Founder Allen Schroeder explained that the problem is that the typical grocery store, for example, creates two types of organic waste:
> Food scraps, food that is no longer edible, soiled paper - this is a great candidate for composting
> Food that is still safe to eat, but has been taken off the shelves because of unsightly bruises or because it's slightly past the sell-by-date (but not actually gone bad) - this is food that, as a volunteer, Schroeder already picks up from some local grocery stores and donates to nonprofit organizations that feed the hungry. Now, Schroeder wants to ensure that this edible food is saved and donated at all grocery stores across the city. 
> This whole idea comes back to the Food Waste Hierarchy, a concept often used within the environmental community to ensure that food waste always goes to the highest and best use. 
> 
> The Food Waste Heirarchy
> With so many people in Austin in need of better access to food, Schroeder hopes that the new ordinance will not only reduce the amount of waste that we send to the landfill, but will also fill an important community need. 
> 
> Right now, the Save The Food Coalition is in the research and coalition-building phase. If you would like to learn more about the coalition, or get involved with its efforts, you can check out their website here>>https://www.savethefoodaustin.com/?utm_source=Austin+EcoNewsletter&utm_campaign=3e55370329-EN11%2F9%2F17_SaveFood_RecyclesDay_2Jobs&utm_medium=email&utm_term=0_e376911220-3e55370329-171090565
>

**Comment by VictoriaODell** [comment]
folks over at #119 brought up a similar idea with less info. An opportunity here to collaborate if possible.

**Comment by ataetemadi** [comment]
Sounds good! Thanks!

**Comment by mscarey** [comment]
Seems like this discussion settled on helping with existing initiatives rather than starting a new project. That's good.
