### ISSUE TITLE
City council meeting - staff costs

### ISSUE THREAD

**Issue by davemcphee** [open-austin/project-ideas#45]
An issue city staff mentioned to me was how during a council meeting, a huge amount of staff are sitting around, waiting for their turn for hours sometimes. 

The idea is to find out what staff is at a meeting waiting for their item, and then use their salary (public) to calculate how much (time/money) is being spent due to council meetings not sticking to a defined agenda order. 

Once some data has been collected, use that data to 
1. Cajole city council to talk about a more structured meeting. Sticking to times (often not possible, I know), sticking to the order of items where possible so you at least have a rough idea when it's your turn, etc
2. Build a #tool to mitigate these wastes of time. Something as simple as restaurant pagers for staff or the public. Your item's coming up next? BZZZZZZT

**Comment by davemcphee** [comment]
Or have an idea of the most "costly" items (10 legal staff, 10 other city staff, 12 members of the public, costing approx $16k per hour of them all waiting around for the same item), and then sort agenda items based on those numbers. Most expensive one first obviously.

**Comment by amaliebarras** [comment]
@davemcphee hi there! are you currently working on this project, or are you willing to be the point of contact if someone wants to? if so, is there a repo? 

if not, may I tag this idea with "needs leadership" so someone else can move it forward if they'd like?

**Comment by werdnanoslen** [comment]
Messaged @davemcphee on Slack

**Comment by davemcphee** [comment]
Hey all, sorry for not seeing this! I haven't worked on this at all, so feel free to commandeer it.

Main blocker for this was finding out, in advance, which staff would be present  (or, looking back, which staff where present, and for how long).

**Comment by mscarey** [comment]
This would need a lot of city council buy-in, and Open Austin is not very engaged with the council lately. I think I'll take the approach of closing the issue and moving the discussion about reopening to #policy.
