### ISSUE TITLE
Additional labels

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/project-ideas#46]
Hey, can we look into adding some labels from this list? [Girl Develop It Labels](https://github.com/girldevelopit/gdi-new-site/labels)

I think the "Beginner Friendly" one is my favorite.

**Comment by VictoriaODell** [comment]
Would also be helpful when I start tweeting out project needs. :bird: :hankey:

**Comment by mateoclarke** [comment]
:+1:

**Comment by luqmaan** [comment]
I like these labels but I don' think they really apply to any of the current issues. Even the `Beginner Friendly` one.
