### ISSUE TITLE
How Might We connect Job Seekers, Educators, Employers

### ISSUE THREAD

**Issue by decibel** [open-austin/project-ideas#49]
#### Concise description. What problem are you trying to solve?

Connect job seekers, educators and employers to:
- Improve communication and connectivity
- break social, economic and racial segregation
- empower people to live their passion in an economically sustainable fashion
#### Link (more details/brain dump/alpha)

![Planning Canvas](https://cloud.githubusercontent.com/assets/235814/13550415/f827e926-e2e2-11e5-8f1c-4eedfd8cb18b.jpg)
#### Who will use/benefit from this project?

Job seekers, employers, educators and subject matter experts (SMEs).
#### Project Needs (dev/design/resources)
- Data on job seeker and employer needs
- Visibility (website/app)
- Dialog/partnership with community groups already providing similar programs
- Connections/partnerships with educators, SMEs and employers
- Facilitators
#### Status (experiment, alpha, beta, official)

Experiment.

Current todo list:
![TODO list](https://cloud.githubusercontent.com/assets/235814/13558302/b335d2e4-e3c6-11e5-8bd5-c6aa4d5be7cb.jpg)

**Comment by mateoclarke** [comment]
Hey @decibel, are you or any of your other team members interested in taking this project to the ATX Hack for Change June 3-5th? If so, all you need to do is submit your idea to the [project proposal Github page](https://github.com/atxhack4change/2016-project-proposals#atx-hack-for-change-2016). Good news is it asks for much of the same info y'all have already filled out here. `@mention` me or shoot me an email if you have any questions at info@open-austin.org.

**Comment by werdnanoslen** [comment]
@decibel how are you doing on this project idea? Any updates since last May?

**Comment by decibel** [comment]
I haven't worked on it. If no one wants to take it over I'd say close it.

**Comment by werdnanoslen** [comment]
Thanks for letting us know! I'll label it so our members know they can pick up and run with this project if they'd like.

**Comment by mscarey** [comment]
It doesn't look like this ever coalesced into a specific idea.
