### ISSUE TITLE
Mayor's Dashboard

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/project-ideas#5]
**One sentence description:**
The Mayor's Dashboard tracks key metrics and outcomes from the City of ~~Los Angeles~~ Austin.

**Link (more details/brain dump/alpha):**
http://datala.github.io/bradley-tower/
https://github.com/datala/bradley-tower

**Project Needs (dev/design/resources):**
Market Validation, would the Mayor's office be interested in this tool?
Front End Dev
Web Technologies: The core technology of existing project is TableTop.js, Bootstrap, Sheetsee.js, and Jekyll

**Status (in progress, pie-in-the-sky)**
Fork Idea

![screen shot 2015-07-06 at 5 00 43 pm](https://cloud.githubusercontent.com/assets/5697474/8534289/92fb689e-2400-11e5-9f51-369820a5143c.png)

**Comment by mscarey** [comment]
I don't think it's possible to think of a single new "Mayor's Dashboard" as a relevant idea for Austin anymore, considering the dashboards currently available at budget.austintexas.gov, transportation.austintexas.io, etc.
