### ISSUE TITLE
Increase internet infrastructure efficiency 

### ISSUE THREAD

**Issue by Harefoot** [open-austin/project-ideas#52]
### “How Might We” statement
1.  How might we increase internet infrastructure efficiency because we know some public networks lock guest access for public internet?
### Who will benefit (directly and indirectly) from this project?
1.  Visitors (tourists)
2.  Visitors (businesses)
3.  Young professionals / students
4.  Low Income
5.  Homeless
### Links to any research/data available/ articles

http://www.nydailynews.com/news/national/new-york-start-replacing-payphone-wi-fi-kiosks-article-1.2485429
### Photo of hack canvas

![highres_447513312](https://cloud.githubusercontent.com/assets/14083988/13550455/ca5ac01c-e2e3-11e5-8c01-cb75ec6c7ed4.jpeg)

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by cnst** [comment]
An updated canvas -- http://www.meetup.com/Open-Austin/photos/26791695/447517070/ http://photos4.meetupstatic.com/photos/event/9/0/c/e/highres_447517070.jpeg

**Comment by mateoclarke** [comment]
Hey @Harefoot, @cnst, are you or any of your other team members interested in taking this project to the ATX Hack for Change June 3-5th? If so, all you need to do is submit your idea to the [project proposal Github page](https://github.com/atxhack4change/2016-project-proposals#atx-hack-for-change-2016). Good news is it asks for much of the same info y'all have already filled out here. `@mention` me or shoot me an email if you have any questions at info@open-austin.org.

**Comment by werdnanoslen** [comment]
@cnst @Harefoot how are y'all doing on this project idea? Any updates since last May?

**Comment by mscarey** [comment]
Looks like more of a discussion, not a task that we need to keep open.
