### ISSUE TITLE
How might we help interested voters get credible, accurate information about how, where and when to vote?

### ISSUE THREAD

**Issue by dheerajchand** [open-austin/project-ideas#53]
### “How Might We” statement

How might we help interested voters get credible, accurate information how, where and when to vote?
### Who will benefit (directly and indirectly) from this project?

End voters
Political parties
Third Party NGO's - advocacy organisations,civic good organisations, etc.
Municipal employees
Elections staff
### Links to any research/data available/ articles

mytexasvotes.org is an example of a similar project done by the Texas Democratic Party
### Photo of hack canvas

![img_20160305_145607262](https://cloud.githubusercontent.com/assets/482844/13550409/d6cb2220-e2e2-11e5-96fe-bd1c68cbc689.jpg)
### What are the next steps (validation, research, coding, design)?
1. Research into voter reg problems,
2. Research into voter file access and costs,
3. Resources assessment: skills, time, interest, servers, designs, etc.

All of that is necessary to figure out how much of the problem we're able to address. Our end hope is not just a website but an API to allow others to piggyback.

**Comment by VictoriaODell** [comment]
Hey @dheerajchand, You said this may drop because of availability. Can you tell me more about the obstacles you're facing? Is the whole team unable to contribute? I'm interested in moving this forward in some way and know a few sites that are addressing voting issues.

**Comment by haileypate** [comment]
Hey, did anyone hear about an app that helps you find the polling place with the shortest line? I tried a brief google search, but no luck. Might be worth looking at to get ideas! I'll keep trying to find it..

**Comment by mateoclarke** [comment]
So Open Austin has a voting place finder app. The main struggle is getting clean data out of Travis County Clerk in a timely manner. App functions fine though (just needs cyclical data updates from the Clerk). @chip-rosenthal was the lead on this project. @avickers helped with the front end.

http://voteatx.us/
https://github.com/open-austin/voteatx-app (front-end client)
https://github.com/open-austin/voteatx-svc (back-end service)

There was also a hackathon project two years ago called ATX Votes (named similar, jaja). They focused more on candidate info and aggregation. I could only find one link about that project, don't think there is a working demo available. 
http://nidhi-reddy.businesscatalyst.com/atx-votes.html

FomoATX.com/vote is another app that got launched for the primaries this March to report poll waiting lines as red or green. A binary red/green metric seemed oversimplified in my opinion but was a cool way to crowdsource wait times and it seemed to be pretty well used on March 1 this year. I used it.
https://twitter.com/EdIreson/status/703593522398507009

**Comment by VictoriaODell** [comment]
There's also http://gotidtexas.org/ voter id questions.

**Comment by VictoriaODell** [comment]
I haven't used it but I saw the creators of this app present a few months ago. I don't know how active they are in developing this. Last I remember I think they were struggling with monetizing it : http://thinkvoting.com/the-voting-app/

**Comment by avickers** [comment]
I have been involved with one of the national campaigns.  The county had a webapp at votetravis.com for the primaries.  After the vote was over it went to a placeholder image of Captain America for awhile, and now just redirects to a generic page.

**Comment by mateoclarke** [comment]
Hey @dheerajchand, are you or any of your other team members interested in taking this project to the ATX Hack for Change June 3-5th? If so, all you need to do is submit your idea to the [project proposal Github page](https://github.com/atxhack4change/2016-project-proposals#atx-hack-for-change-2016). Good news is it asks for much of the same info y'all have already filled out here. `@mention` me or shoot me an email if you have any questions at info@open-austin.org.

**Comment by edireson** [comment]
Not to hijack this issue, but if anyone is interested in pushing something like this forward, I'd love to grab a coffee/beer with you. I'm particularly interested in day-of voting, but there is obviously plenty of interesting efforts that could be made here.

(I'm one-half of FOMO//ATX and did the primaries polling line app. It was thrown together over a weekend, after [reading this tweet](https://twitter.com/LillyRockwell/status/703352050105585664).)

**Comment by VictoriaODell** [comment]
I'm participating an event the end of the month that is related to this issue and am interested to see what comes out of it. [Texas Tribune Turnout.](https://www.texastribune.org/texas-turnout/?utm_source=Texas+Tribune&utm_campaign=b11e6d4160-trib-email&utm_medium=email&utm_term=0_d9a68d8efc-b11e6d4160-101523513&mc_cid=b11e6d4160&mc_eid=75d4c09533) Applications are closed now unfortunately but this is an issue I'm super interested in. 

I think my interest is more around education around voting prior to polling days though. I'm supposed to follow up with Progress Texas to get the GotID website I mentioned earlier updated.

**Comment by mateoclarke** [comment]
I just saw a headline yesterday about Google pushing new features in its search related to voting:
https://techcrunch.com/2016/08/16/google-search-now-includes-info-on-how-to-vote/

**Comment by mateoclarke** [comment]
![](http://dsh.re/2d06d)
https://open-austin.slack.com/archives/general/p1472144813000354

@edireson and anyone else following this thread. It sounds like progress on this type of tool will be moving forward at our [Civic Hack Nights](http://www.meetup.com/Open-Austin/events/233028666/) coordinated by @sya & @avickers.

**Comment by werdnanoslen** [comment]
Hi @dheerajchand & @edireson. Haven't heard much about this idea lately. Do y'all need any resources or help finding people to work on this? Would love to see [the demo](http://voteatx.us/) up and running again; what can I hook you up with to make that happen?

**Comment by werdnanoslen** [comment]
The voteatx.us site is currently up but displays a "not in operation" message to avoid confusing people looking for current voting places. 

To get it back up, work with @chip-rosenthal. From Chip: "The main thing is getting the data from Travis and Williamson County, and load it into the database. Last time I did this, it was a complicated process, requiring manual data entry from WilCo and major data sanitization from Travis."

Also see the issue for this on the repo: https://github.com/open-austin/voteatx-app/issues/28#issuecomment-338519803

**Comment by mscarey** [comment]
Closing this because voting info is a relatively fast-moving field, so I think any new efforts here would have to start over at the research phase.

**Comment by avickers** [comment]
As an addendum, I would like to point out that there are national nonprofits that provide apps with this functionality.  They have the resources and clout to collect and sanitize the data.  If this issue is ever addressed by Open Austin again, I would encourage participants not to view it as a technical challenge, requiring an engineering solution, but rather as an awareness / marketing challenge to help local voters find those existing solutions.
