### ISSUE TITLE
Cultural Assets Census

### ISSUE THREAD

**Issue by JuddRogers** [open-austin/project-ideas#55]
### “How Might We” statement

How might we help citizens identify cultural assets because they are at risk of being lost and Austin appeal/quality of life is closely tied to its cultural cache.
### Who will benefit (directly and indirectly) from this project?

City Planners/Policy Makers
Artists/Content Creators
Community Groups
Venue and Exhibition space owners
Citizens (Audiences)
Tourists
### Links to any research/data available/ articles

TBD
# Planning Canvas
## Problem Statement

We are losing our cultural assets
- No clear defection of what our cultural assets are
- Don't have an inclusive way to identify assets
- Don't have clear policies to maintain Austin's cultural assets
- Don't have a way to express their value
- No way to determine economic value of assets
## Users and Those Impacted

City Planners/Policy Makers
Artists/Content Creators
Community Groups
Venue and Exhibition space owners
Citizens (Audiences)
Tourists
## Project
- Census of Cultural Assets
- Solicit input of what to map/include in census on-line
### Criteria
- an inclusive definition of "cultural asset"
  - users can put in _any_ point
### Metrics
- Number of users
- geographic distribution of users
## Features and Benefits
- Web-site with interactive map
  - crowd sourced map
  - annotated map
- Filter and categorize map
- Mobile App to tag your Cultural Asset
  - "hello lamp-post"
- Download points themselves for participants to use
- Report/Map to download
- Easy and fun to use!
## Key Activities
- Find city data sets
- Find host (servers)
- User Experience (UX) design
- data design
- marketing
  - city
  - newspapers
## Key Resources
- CoA Advocates
- City data
- Web App Design and Development
- Mobile App Design and Development
- common backend to save, get data Design and Development
## Partners
- CoA Cultural Arts Division
  - contact: Shirley Rempe
- Comminity Groups
- City Counsel
# Photo of hack canvas
# What are the next steps (validation, research, coding, design)?

Validate CoA interest

Recruitment.

Find data sets

**Comment by JuddRogers** [comment]
How might we:
![image](https://cloud.githubusercontent.com/assets/5130120/13550562/6e534d5e-e2e6-11e5-963c-37e4bcbcfd99.jpeg)

Planning Canvas
![image](https://cloud.githubusercontent.com/assets/5130120/13550570/ae770b28-e2e6-11e5-9306-c1fa69f51ef1.jpeg)

**Comment by Shirley-R** [comment]
We have a dataset of the Cultural Arts Division's cultural assets, but want to see that list grow as we hear from others about what they consider to be their cultural assets!

[PG Poster.pdf](https://github.com/open-austin/project-ideas/files/176407/PG.Poster.pdf)

**Comment by mateoclarke** [comment]
Hey @Shirley-R, @JuddRogers, @haileypate, are you or any of your other team members interested in taking this project to the ATX Hack for Change June 3-5th? If so, all you need to do is submit your idea to the [project proposal Github page](https://github.com/atxhack4change/2016-project-proposals#atx-hack-for-change-2016). Good news is it asks for much of the same info y'all have already filled out here. `@mention` me or shoot me an email if you have any questions at info@open-austin.org.

**Comment by amaliebarras** [comment]
Hey @Shirley-R, I'm cleaning up the project ideas repo and want to add a status update to this thread. I know you came to a few hack nights to recruit last year, were you able to get anyone to work on it? Is there a repository of work I can link to in the README?

**Comment by werdnanoslen** [comment]
Messaged @Shirley-R on Slack

**Comment by VictoriaODell** [comment]
This project was completed: 
https://culturalarts.carto.com/builder/12beee5f-3c8e-40fd-ae9c-8ce109a1bb87/embed

I don't have the full story but here is more info: 
http://www.austintexas.gov/department/cultural-asset-mapping-project

Marking this as inactive. We should dig deeper and see what came of this.

**Comment by mscarey** [comment]
Closing because the project was completed.
