### ISSUE TITLE
Affordable, Healthy Food

### ISSUE THREAD

**Issue by lalaloosay** [open-austin/project-ideas#57]
### “How Might We” statement

How might we help consumers access more fresh, nutritious food because we know that it seems expensive.
### Who will benefit (directly and indirectly) from this project?

Single-working parents, communities at the poverty level, the elderly, immigrant populations and refugees
### Links to any research/data available/ articles

http://sustainablefoodcenter.org/
http://sustainablefoodcenter.org/get-involved/fresh-seasonal-recipes
http://www.ers.usda.gov/media/600474/eib96.pdf
### Photo of hack canvas

![20160305_144826](https://cloud.githubusercontent.com/assets/15808546/13550391/4eb09014-e2e2-11e5-9730-f62e56efa191.jpg)
### What are the next steps (validation, research, coding, design)?

Locating people with the skill sets to execute the following:
- Nutritionist who can educate our targets about healthy food
- Data scientists to obtain and figure out healthy food metrics
- Business Development/Marketing/Outreach person to form partnerships with nonprofits to obtain data and local food providers to set up strategic pricing
- Mobile developers
- UI/UX designers to create the website or mobile app
- Photographers for taking pictures of food

**Comment by EllenLazaretti** [comment]
Additional references: 
http://stretchrecipes.com/about/
http://itstimetexas.org/livinghealthier/

**Comment by mateoclarke** [comment]
Hey @EllenLazaretti & @lalaloosay , are you or any of your other team members interested in taking this project to the ATX Hack for Change June 3-5th? If so, all you need to do is submit your idea to the [project proposal Github page](https://github.com/atxhack4change/2016-project-proposals#atx-hack-for-change-2016). Good news is it asks for much of the same info y'all have already filled out here. `@mention` me or shoot me an email if you have any questions at info@open-austin.org.

**Comment by werdnanoslen** [comment]
This project has been picked up in spirit by Fresh for Less as @poplav referenced. @lalaloosay are you interested in working with that team, or is this Affordable, Healthy Food project something unique from that?

**Comment by werdnanoslen** [comment]
@sya could you take a look at this project and see if there's something #83 could merge this in or stay separate?

**Comment by VictoriaODell** [comment]
Just want to follow up with some info that was sent from Austin Eco Network that is relevant to this. 

> [Food/Zero Waste] In Travis County (where Austin is located) 18 percent of the population and 25 percent of the children are food insecure. This means that they don't know where their next meal will come from. Meanwhile, 194.5 million pounds of food (worth more than $208 million) is wasted annually in this city.
> 
> So how do we fix this imbalance? A new group of activists are hoping to create a solution. The Save The Food Coalition is working to create a new city ordinance that will require restaurants and businesses to donate or sell their leftover (but still edible food), instead of just throwing it away or composting it.
> 
> Save The Food Coalition is trying to pass a new ordinance in Austin.
> 
> But wait, isn't this already happening?
> Our city already has a policy that requires food-related business to divert organic waste from the landfill. They can do this in a number of ways, including by donating food, composting, and simply reducing the amount of waste produced in the first place. This is a part of the Universal Recycling Ordinance, which has been popular within the environmental community, but as the Save The Food Coalition sees it, there are even more opportunities to serve the community and reduce waste at the same time. 
> 
> In a Facebook Live interview with the Austin EcoNetwork earlier this week, Save The Food Coalition Founder Allen Schroeder explained that the problem is that the typical grocery store, for example, creates two types of organic waste:
> Food scraps, food that is no longer edible, soiled paper - this is a great candidate for composting
> Food that is still safe to eat, but has been taken off the shelves because of unsightly bruises or because it's slightly past the sell-by-date (but not actually gone bad) - this is food that, as a volunteer, Schroeder already picks up from some local grocery stores and donates to nonprofit organizations that feed the hungry. Now, Schroeder wants to ensure that this edible food is saved and donated at all grocery stores across the city. 
> This whole idea comes back to the Food Waste Hierarchy, a concept often used within the environmental community to ensure that food waste always goes to the highest and best use. 
> 
> The Food Waste Heirarchy
> With so many people in Austin in need of better access to food, Schroeder hopes that the new ordinance will not only reduce the amount of waste that we send to the landfill, but will also fill an important community need. 
> 
> Right now, the Save The Food Coalition is in the research and coalition-building phase. If you would like to learn more about the coalition, or get involved with its efforts, you can check out their website here>>https://www.savethefoodaustin.com/?utm_source=Austin+EcoNewsletter&utm_campaign=3e55370329-EN11%2F9%2F17_SaveFood_RecyclesDay_2Jobs&utm_medium=email&utm_term=0_e376911220-3e55370329-171090565
>

**Comment by mscarey** [comment]
Closing because the project doesn't seem to have settled on a course of action, other than locating other people with the knowledge needed to make a plan.
