### ISSUE TITLE
Civic Focused Project Marketplace for Freelancers in Austin

### ISSUE THREAD

**Issue by ryegrammer** [open-austin/project-ideas#58]
### “How Might We” statement

How might we help creatives connect with volunteers, businesses and non-profits.
### Who will benefit (directly and indirectly) from this project?

The community, developers, businesses and non-profits
### Links to any research/data available/ articles

None currently and still in progress.
### Photo of hack canvas

![img_4425 2](https://cloud.githubusercontent.com/assets/4467354/13550461/e47ac8b6-e2e3-11e5-84e8-3bf006aa96e5.JPG)
### What are the next steps (validation, research, coding, design)?

Research the interest and viability of the participants: workers and organizations. Wireframes and prototyping. Determine code frameworks to create CMS and login verification systems. API Integration of civic-minded job sites to pull project information.

**Comment by mateoclarke** [comment]
Hey @ryegrammer, are you or any of your other team members interested in taking this project to the ATX Hack for Change June 3-5th? If so, all you need to do is submit your idea to the [project proposal Github page](https://github.com/atxhack4change/2016-project-proposals#atx-hack-for-change-2016). Good news is it asks for much of the same info y'all have already filled out here. `@mention` me or shoot me an email if you have any questions at info@open-austin.org.

**Comment by werdnanoslen** [comment]
This is something I was considering re:legal organization @jonplaca  @mateoclarke 
@ryegrammer are you still interested in this project?

**Comment by jonplaca** [comment]
@werdnanoslen Sorry, I do not understand your comment. How is this related to Legal Formation?

**Comment by werdnanoslen** [comment]
like how can we organize ourselves for freelancers to get involved in our projects for pay. It was the reason I was interested in the coop model

**Comment by jonplaca** [comment]
I see. I think a list like this would be useful not only for freelancers, but also for Open Austin to build relationships with local companies that are in need of assistance. Currently I have two major projects on my plate, but would be willing to support this from the peripheral if someone took lead. 

As a side-note: payments aren't restricted to co-op structures. We can discuss in more detail at the next meeting.

**Comment by mscarey** [comment]
Oh, is this why we formed a nonprofit? I guess this project is completed then.
