### ISSUE TITLE
How might we increase the impact & awareness of xeriscaping with homeowners? 

### ISSUE THREAD

**Issue by ZeshanNSegal** [open-austin/project-ideas#59]
#### Concise description. What problem are you trying to solve?

Lack of awareness about water conservation and xeriscaping. And, to create lasting environmental change by increasing community engagement. Watershed Protection. 

Tell us what problem you're trying to solve.
#### Link (more details/brain dump/alpha)

https://data.austintexas.gov/browse?Additional-Information_Department=Austin+Water&Type=%5Bobject+Object%5D&q=water&sortBy=relevance&utf8=%E2%9C%93

http://www.examiner.com/article/city-of-austin-waterwise-landscape-rebate-program-conserve-water-and-save-money

https://www.austintexas.gov/faq/xeriscaping

http://www.austintexas.gov/department/water-conservation

http://www.austintexas.gov/department/austin-daily-water-usage

http://www.mysanantonio.com/community/southside/news/article/Converting-to-a-xeriscape-landscape-not-that-hard-3402973.php

https://data.austintexas.gov/Utility/Austin-Water-Statistics/87qq-mkwq

https://data.austintexas.gov/Environmental/Water-Quality-Sampling-Locations-Map/4abv-9q7r

https://data.austintexas.gov/Environmental/Watershed-Regulation-Areas/4sak-tmrs

https://data.austintexas.gov/Environmental/Map-Austin-Small-Scale-Green-Infrastructure/8539-u3jx

http://www.austintexas.gov/department/drainage-charge-estimator

http://kxan.com/2014/06/17/top-water-users-in-the-city-of-austin/

http://www.examiner.com/article/city-of-austin-waterwise-landscape-rebate-program-conserve-water-and-save-money

![xeriscape_canvas3](https://cloud.githubusercontent.com/assets/14319946/13550480/4774df7e-e2e4-11e5-9551-cf418db06e48.jpg)
![xeriscape_canvas2](https://cloud.githubusercontent.com/assets/14319946/13550481/49f25bfa-e2e4-11e5-90ec-f5f0456e6e95.jpg)
![xeriscape_canvas1](https://cloud.githubusercontent.com/assets/14319946/13550482/4bc4e07e-e2e4-11e5-9e13-8b461cac2e36.jpg)

neighborhood partnering program

Add a link here.
#### Who will use/benefit from this project?

-- Homeowners, neighborhoods, mother nature, the city of austin, local nurseries, communities. 
-- Homeowners will use technology(our app) to learn about native species, how to convert to xeriscape, 
community meetups, connect with other local xeriscapers, feedback and voting on landscape, creating social aspect and friendly competition to benefit our ecosystems. 

Explain who will use and benefit from this project.
#### Project Needs (dev/design/resources)

---Developers, designers, city of austin- resource- Parks Foundation (non-ptofit, separate from city), City zoning and planning commission Neighborhood Plan Map (each neighborhood has their own and can request projects through there, especially creeks) knowledgable green thumbs, volunteers
### **#Next Steps**:

Validation, check need with COA
#### Status (experiment, alpha, beta, official)

experiment

Add the status of the project here.

**Comment by mateoclarke** [comment]
Hey @ZeshanNSegal, are you or any of your other team members interested in taking this project to the ATX Hack for Change June 3-5th? If so, all you need to do is submit your idea to the [project proposal Github page](https://github.com/atxhack4change/2016-project-proposals#atx-hack-for-change-2016). Good news is it asks for much of the same info y'all have already filled out here. `@mention` me or shoot me an email if you have any questions at info@open-austin.org.

**Comment by werdnanoslen** [comment]
Echoing Mateo's comment above, Hack for Change is back again this year. @ZeshanNSegal are you interested in taking this there?

**Comment by mscarey** [comment]
I think this project idea became [xeritopia](https://github.com/mapineda/xeritopia), which was sort of completed.
