### ISSUE TITLE
website and service monitoring solution

### ISSUE THREAD

**Issue by chip-rosenthal** [open-austin/project-ideas#6]
**One sentence description:**

setup a monitoring solution to alert if a website or web service goes down

**Link (more details/brain dump/alpha):**

Either a hosted service or a tool running in an (e.g.) Amazon EC2 instance would be preferred.

This probably should NOT run on the open-austin.org server -- that's one of the things we'd like to monitor.

**Project Needs (dev/design/resources):**

A volunteer with admin skills.

Need to develop a plan, including a set of URLs to be monitored, as well as contacts in the case of outages.

**Status (in progress, pie-in-the-sky)**

Proposed.

Chip is currently monitoring data.austintexas.gov thru montastic.com

**Comment by luqmaan** [comment]
Maybe https://www.pingdom.com/free?

**Comment by chip-rosenthal** [comment]
done
http://www.open-austin.org/hack-team/service-status

**Comment by luqmaan** [comment]
:night_with_stars::fireworks::fireworks::fireworks::fireworks::star2::fireworks::fireworks::fireworks::fireworks::night_with_stars:


Our first completed project idea!
