### ISSUE TITLE
Open FEC Campaign Finance Data

### ISSUE THREAD

**Issue by robertsosinski** [open-austin/project-ideas#64]
### What problem are we trying to solve?

Understanding the federal election process by analyzing campaign finance data.
### Who will benefit (directly and indirectly) from this project?

The American People, especially those interested in how campaign donations affect the political process. 
### Links to any research/data available/ articles

https://beta.fec.gov
https://api.open.fec.gov/developers/
https://github.com/18F/openFEC
https://github.com/18F/openFEC/issues
### What are the next steps (validation, research, coding, design)?

Making new services or visualizations with this data.  This could involve coding and/or design.
### What help is needed at this time?

OpenFEC API is open source, with issues on GitHub. Feel free to submit pull requests for code or documentation changes.  Also, create a new issue if you see something you would like to change!

**Comment by mscarey** [comment]
There's no reason we can't do exclusively federal projects, but a link to local politics might make this easier for us. We might think about a way to limit it to deeper research of Texas candidates for federal offices (or even just central Texas).

**Comment by mscarey** [comment]
I'm sure there's stuff to find in these databases, though it starts to cross the line into trying to be a news organization.
