### ISSUE TITLE
Austin Clubhouse services curator/aggregator 

### ISSUE THREAD

**Issue by schludermann** [open-austin/project-ideas#65]
### What problem are we trying to solve?

A bit of background is in order. The Austin Clubhouse exists to provide acceptance and empowerment so adults living with mental health diagnoses can pursue personal goals and play a meaningful role as co-workers, colleagues, family members and friends. Towards this goal the Austin Clubhouse serves as a place for meaningful activities and connects Clubhouse members with health, social, transportation, housing, financial and other services in the surrounding community. The Clubhouse is not a clinical organization, no treatments are offered and there is no clinical staff. The Clubhouse is staffed by social workers.

The Problem is that members need help outside of the normal Clubhouse operations. The Clubhouse provides services 9-5 weekdays, in-house. It can also be a burden for members to access these services with scheduling and transportation issues and because they have started to work.

Providing members with access to the usual range of services after hours and off-site can make all the difference to a member's state of mind. 
### Who will benefit (directly and indirectly) from this project?

Immediately, there are over 600 Austin Clubhouse members. If well designed and implemented, this project could be adopted  by up several hundred Clubhouses worldwide.  The community will benefit from timely assistance. 
### Links to any research/data available/ articles

HTTP://www.AustinClubhouse.org
### What are the next steps (validation, research, coding, design)?

Currently the project is polling members for their input and designing the layout of the project
### What help is needed at this time?

How to organize the findings into a package that developers can use to create a smartphone app and extended the Austin Clubhouse homepage to reflect these services.

**Comment by ssharif1** [comment]
http://www.open-austin.org/civic-tech-canvas/

**Comment by filmmoneypower** [comment]
interesting problem let's do it.

**Comment by schludermann** [comment]
will there be some sort of meeting on this?

**Comment by filmmoneypower** [comment]
good question lets talk  512.228.2576 give me a call

**Comment by amaliebarras** [comment]
hi @filmmoneypower @schludermann , did you ever meet to discuss this project? what was the outcome? what help is needed at this time?

**Comment by schludermann** [comment]
The clubhouse never even acknowledged the suggestion. So ditch the whole thing.

**Comment by amaliebarras** [comment]
Sorry to hear that! The [civic tech canvas](https://github.com/open-austin/civic-tech-canvas) is a great way to frame your idea and then communicate to the people you want to serve, and works as a great tool for recruiting project help as well.

**Comment by werdnanoslen** [comment]
@amaliebarras if this project's been ditched but could be salvageable, should we keep `needs leadership` and `abandoned and needs love` labels?

**Comment by schludermann** [comment]
I shopped this to several non-profits over the last year, the latest the to new dell medical hospital and they seem to be under the impression that 1990’s style landline programs are sufficient for the indigenous homeless and poor.
Since I don’t have the appetite to convince the army of neurotypicals in charge of programs that there are more appropriate technologies for the poor, I would say ditch the idea. I’ve moved on.

Kris

**Comment by werdnanoslen** [comment]
I know what you mean Kris, changing policy and general culture can be hard, but I'd like to keep the idea open in case others manage to make a breakthrough. I'll set it as `needs leadership` so others can continue trying to make this happen. :)

**Comment by mscarey** [comment]
closing because the prospective client is not onboard
