### ISSUE TITLE
Community Data Portal

### ISSUE THREAD

**Issue by wilsaj** [open-austin/project-ideas#66]
### What problem are we trying to solve?

We need a data portal by the peeps for the peeps :hatching_chick: - credit goes to @mateoclarke for the idea!

Sometimes we come across datasets that need a good home. These can be data published by NGOs and governments, data generated by other Open Austin projects, or just dumps of data from information requests. Some good examples are the datasets on http://data.open-austin.org/

There are two parts to this:
1. Organizing what we know about these datasets so they are easy to sift through and find.
2. Hosting for datasets that are not otherwise publicly available. S3 would be good for this, but there are other options as well.

The community data portal is not really intended to compete or even overlap with existing data portals like the ones run by [City of Austin](https://data.austintexas.gov) or the [State of Texas](https://data.texas.gov/). Instead, this would provide similar functionality for datasets that come from places that don't already have an adequate data portal.
### Who will benefit (directly and indirectly) from this project?
- People, non-profits and government agencies that want to publish open data but don't have anywhere to put it.
- Anybody who wants to get open data from people, non-profits and government agencies that want to publish open data but don't have anywhere to put it.
### Links to any research/data available/ articles
- JKAN: https://github.com/timwis/jkan
- CKAN: http://ckan.org/
- DKAN: https://www.drupal.org/project/dkan
### What are the next steps (validation, research, coding, design)?

We have [a fork of JKAN](https://github.com/open-austin/data-portal) currently set up that we can start experimenting with. Simplicity and low-maintenance are high priorities, and JKAN targets those explicitly so that seems like the best place to start.
### What help is needed at this time?

Feedback on JKAN and how it is currently set up would be great (Does it fit our needs? Does the infrastructure / architecture look alright?). Assuming this is the road we want to take, then there will be some design and coding work to customize and imbue it with Open Austin awesomeness.

Update: this project is no longer active. Project story is [here](https://www.open-austin.org/projects/community-data-portal.html)

**Comment by amaliebarras** [comment]
### Yay PANDA! 🐼 

The live Open Austin data portal is [here](http://www.open-austin.org/data-portal/)
Github repo associated with the live thing is [here](https://github.com/open-austin/data-portal)
I forked the portal for the design and have been working out of [here](https://github.com/amaliebarras/data-portal-new)
Link to portal design (PANDA 🐼 ) is [here](https://github.com/amaliebarras/data-portal-new)

#### Plans for ATXHackforChange: 
Take out dummy data & test the jekyll loops
Add project schema 
Figure out functionality for vote
Merge design code into open austin site
Make sure login button works once deployed

**Comment by werdnanoslen** [comment]
@amaliebarras @wilsaj is this project complete? Is there anything more to be done?

**Comment by mateoclarke** [comment]
There is a pretty good project summary on our website:
https://www.open-austin.org/projects/community-data-portal.html

I would call this "status: experiment" & "inactive"
If anything, the work moving forward would be publishing more data on data.world and that could be it's own project idea based on the data.

**Comment by werdnanoslen** [comment]
Sweet, so this is like a continuous delivery vs 'done' sort of project. Is it inactive because nobody's focusing on it right now, or is there something in the way?

**Comment by mateoclarke** [comment]
I was say it is done because we have a good place to put data we want to share with the public.

There is more to be done in actually publishing the data now.

**Comment by wilsaj** [comment]
I think we can call this done.
