### ISSUE TITLE
Building Permit App

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/project-ideas#68]
### What problem are we trying to solve?

Austin [Development Services Department](http://www.austintexas.gov/department/building-permits) handles building permits for the city. Currently, it's hard for people to find out if they need a permit and if so what application and steps they need to do before turning one in. It's also difficult for city employees to find the correct form despite knowing what is needed. 

If we could make the process easier we could help save people time, money, and frustration and help expedite the permitting/ building process. 

The current page for permitting is mostly a list of links and text that tries to take you to different pages and pdfs. [View it here](http://www.austintexas.gov/department/building-permits). 
### Who will benefit (directly and indirectly) from this project?
- Development Services Employees
- Austin Citizens working to renovate their homes
- Local builders lol or something
### Links to any research/data available/articles

This project was started at ATX Hack for Change with the[ project repo](https://github.com/open-austin/permit-server) currently living in the Open Austin organization. 

The current prototype can be found [here](https://permit-wiz.herokuapp.com/)

We did some light research and it's documented in these [Google Slides](https://docs.google.com/presentation/d/1_F6QcG47xNiylen5K9aDNTVXFmAtFBellnkaTSSGfFw/edit#slide=id.p)
During the weekend we went over the scope for the hackathon, did some research on existing or similar solutions, and outlined some basic content. For the Hackathon we focused on figuring out if people would qualify for an express permit specifically. 

We also have a [google doc](https://docs.google.com/document/d/1FjVgvwwzJd3qWWKOiyXG3Zxr45ad4eFuBIVMGWivL_c/edit?usp=sharing) with some notes. 

Further ideation and design work can be found in our project repo [design-docs](https://github.com/open-austin/permit-server/tree/master/design-docs) folder

[Homebasefix.com](http://www.homebasefix.com/) - Something super similar was done by CfA Fellows in San Antonion and we should really check out what they did before doing any further work. 
### What are the next steps (validation, research, coding, design)?

This is a valid project~ The orignial project champion for the hackathon was a city employee(Julia Robbins) with first-hand experience with the frustration caused by permitting. The city of Austin also mentioned permitting as something that innovation fellows may work on as a project in a recent email.

Before we dive deeper into coding and design we need to do some further research on the permitting process, gather some user stories and feedback on the current process, and also see if we can get any analytics. 
### What help is needed at this time?

UX help is most needed currently with an emphasis on research. If we want to build a solution fit for the city we need to first examine what is needed and prioritize.

**Comment by VictoriaODell** [comment]
Open Austin Slack channel for this project: https://open-austin.slack.com/messages/permitting/

**Comment by VictoriaODell** [comment]
Latest Repo: 
https://github.com/open-austin/permit-prereq-check

We are focusing specifically on pre-req requirements for permitting.

**Comment by amaliebarras** [comment]
Status: "We are paused indefinitely.  The city has fellows currently working on permitting and we faced some data roadblocks."

**Comment by VictoriaODell** [comment]
City fellows created this: 
http://permittingatx.com/

And used our prototypes and some of our research as a reference.

**Comment by mscarey** [comment]
Seems like this can be consider finished.
