### ISSUE TITLE
Get @CutePetsAustin bot working again

### ISSUE THREAD

**Issue by luqmaan** [open-austin/project-ideas#76]
https://twitter.com/cutepetsaustin is a bot that tweets lost animals

It used to run as a cron job, but that stopped working.

Is anybody interested in setting up @CutePetsAustin to run daily through AWS Lambda?

https://github.com/open-austin/CutePetsAustin

**Comment by scascketta** [comment]
I can work on this. I just need the Twitter credentials for the @CutePetsAustin account. Alternatively, I need the `aws-openaustin.pem` file so I can access the existing EC2 instance to get the credentials there.

**Comment by scascketta** [comment]
Completed in https://github.com/open-austin/CutePetsAustin/pull/7 .
