### ISSUE TITLE
Mobile reporting boilerplate (mobile-map-io)

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/project-ideas#80]
### What problem are we trying to solve?

Wasted time reinventing the wheel. The wheel is any mobile reporting application.
### Who will benefit (directly and indirectly) from this project?

Developers who build mobile reporting apps, people with ideas that want to quickly prototype something.
### Links to any research/data available/articles

[http://andyhub.com/concepts/mobile-reporting/](http://andyhub.com/concepts/mobile-reporting/)
[https://github.com/werdnanoslen/mobile-map-io](https://github.com/werdnanoslen/mobile-map-io)

### What are the next steps (validation, research, coding, design)?
Fork the project and do something with it. Could be finding events, mapping free food, reporting broken street lights, etc.

**Comment by werdnanoslen** [comment]
I've made a big update to this project, it now has a bunch of performance, design, usability, and feature updates. See my dumpster diving app as an example of what you can do with this project: https://github.com/werdnanoslen/gleanhub/releases/tag/0.2

**Comment by werdnanoslen** [comment]
So this isn't really a project idea anymore, as it's in a fairly finished state and now in maintenance mode. But I see people referencing it in issues. Should this be closed and the app advertised in another way?

**Comment by amaliebarras** [comment]
I don't see any harm in keeping it open and it would be a lot to track down all the places it's referenced. Maybe if you wanted to add a status note at the top of the issue?

**Comment by VictoriaODell** [comment]
Hey, been a minute but doing some cleanup. Since this is done this, can probably go to our projects page now: https://www.open-austin.org/projects/

Thoughts @mscarey and @werdnanoslen ? :) Hope you're well, Andy.

**Comment by VictoriaODell** [comment]
We can mark it as an experiment and link to the resources you created + this original issue.

**Comment by werdnanoslen** [comment]
hiiii yeah go for it, i'm no longer updating it, but i will respond to anything about it and maintain when someone requests
