### ISSUE TITLE
Texas Justice Initiative

### ISSUE THREAD

**Issue by awoog** [open-austin/project-ideas#81]
### What problem are we trying to solve?

Increase access to information on who died in police encounters and jail and prison custody in Texas.
### Who will benefit (directly and indirectly) from this project?

General public, researchers, policymakers, journalists.
### Links to any research/data available/articles

http://www.texasjusticeinitiative.org
### What are the next steps (validation, research, coding, design)?

Website update and additional features.
### What help is needed at this time?

Update data, add search feature, possibly add mapping.

**Comment by laconc** [comment]
The full dataset is currently hosted [here](https://data.world/tji/tx-deaths-in-custody-2005-2015) at data.world.

We could use assistance in analyzing the data and coming up with some new conclusions.

**Comment by dheerajchand** [comment]
Interested.

**Comment by laconc** [comment]
That's fantastic Dheeraj! Since your interest is in the data analysis, would you mind continuing the conversation on [data.world](https://data.world/tji/tx-deaths-in-custody-2005-2015/discuss/2359)? I would love to know what kind of pattern immediately jumps out at you.

**Comment by kgarrett** [comment]
I think another interesting component to this dataset is geographical and would be an excellent addition to the website. Include death_city as a filter? Could add Google Fusion map with death_address with longitude/latitude?

**Comment by amaliebarras** [comment]
Awesome! We actually have been discussing exactly this in Slack. Are you in that channel?

**Comment by kgarrett** [comment]
@amaliebarras Hmm... I was added to several channels today at the hackathon. Not sure about one for this specific project

**Comment by dheerajchand** [comment]
If you find the channel, please invite me to it. @dheerajchand is my ID.

**Comment by amaliebarras** [comment]
what's the status on this project? @seandellis I think you and Selene were working on it as recently as November 8?

**Comment by seandellis** [comment]
I haven't heard back from the project champions since November when I had
shared a map of their dataset with them.

I'll follow up with them.

**Comment by seandellis** [comment]
@amaliebarras I reached out on 3/3/17, but still haven't heard back. I'd recommend archiving the project.

**Comment by mistynodine** [comment]
So, what is the status of this at this point?

**Comment by seandellis** [comment]
@mistynodine Yes, that's the latest file.

I was the last one to work on it by populating blank counties and adding latitude and longitude. I have the full edit history within OpenRefine if anyone wants to verify the edits.

I don't think there's anything else that needs to be done on the data set. I think Open Austin's role on the project is finished and should be marked as such.

But if anyone wants to analyze the data, it's ready for them to do so.

**Comment by mscarey** [comment]
our work here is done
