### ISSUE TITLE
Austin Healthy Food Access - Fresh for Less

### ISSUE THREAD

**Issue by sya** [open-austin/project-ideas#83]
### What problem are we trying to solve?
**1.**  
**Healthy food locations**
  * Help communities in need of healthier food options find 'healthy food locations' near them
  * Develop dynamic maps based on the locations   

**2.**  
**SNAP Application**
* Assess what makes the SNAP process so arduous, why aren't people using their SNAP benefits?
* Make the SNAP application an easier process for Austin residents

### Who will benefit (directly and indirectly) from this project?

Communities throughout Austin that 1. Use SNAP or 2. Want to find healthy food near them

### Links to any research/data available/articles

![food_access](http://i.imgur.com/EowWWJ6.png)

* [data.world/austin](https://data.world/cityofaustin/fresh-for-less)
* [Google Doc with Initial Planning and Brainstorming](https://docs.google.com/document/d/1RG70lSEz3I8-pDOXvvnNB9jfvcxgJ0lacO3MibpuVi8/edit?usp=sharing) 
* If you're interested, please join our Slack Channel in Open Austin #freshforless

### What are the next steps (validation, research, coding, design)? 

* User design research (shadow 'Guardians' that help clients sign up for SNAP)   
* Comparative Analysis with [GetCalFresh's work](https://github.com/codeforamerica/clean/wiki/CalFresh-Information)
-Note: Their repo is now private :( _ 

### What help is needed at this time?

* Frontend developers   
* Researchers finding data to overlay

**Comment by Woodley** [comment]
Please define Communities. When you state communities all over Austin does
this include those without income, homeless, disabilities, low income,
those unable to obtain SNAP (food stamps), those that use SNAP (food
Stamps), WIC, etc... or does this only benefit those

In what way are you seeking to find healthier food options?
Restaurants?
Locating Food pantries? and the hours of operation.
Locating Charitable food places?
Location of non-profit kitchens?
Location of food drives?
Location of urban food farms? and how to rent spaces for growing your own
foods.

How would you get information and data about these places? Is there a
registration process to include events, and information?

I think this is a much needed data. We have people locally that have little
or no access to foods much less healthy foods.

Kind Regards,
John Woodley
Advocate for Disability Access

**Comment by werdnanoslen** [comment]
data is at https://data.world/cityofaustin/fresh-for-less

**Comment by grantnorwood** [comment]
I'm interested in donating my time as a front-end/full-stack developer to improving access to healthy foods, and have cruised the data.world site and read what data seem to be currently available.  However, I'd like to know more about what ideal solutions have been researched so that I can think about how an app might solve some of the problems defined.

Solutions seem to revolve around location-based data & maps, and a directory of stores with healthy food available, but I'm sure there's more an app could do to improve access to healthy foods in certain zip codes.

Is there someone leading this effort who would like to discuss this project with me?

**Comment by poplav** [comment]
What is the current state regarding this proposal?  I am interested.  
There seems to be overlap with another issue https://github.com/open-austin/project-ideas/issues/57

**Comment by mateoclarke** [comment]
@grantnorwood & @poplav, The best place to join in and see what help might be needed is in the Slack channel this group started.

https://open-austin.slack.com/messages/freshforless

Go to slack.open-austin.org if you haven't joined the Slack yet. Once you're there `@sya` and `@andy` will have the most info regarding the state of the project.

Best,
Mateo

**Comment by sya** [comment]
Hello @grantnorwood and @poplav I apologize for the radio silence! I've updated the project info. After some back and forth with the city we have a lot more direction. 
1. Is a project we can definitely work on and we will have data for in April. We can start building the infrastructure for already (MAP-BASED TOOLS, SOME WEB DEVELOPMENT, etc)
2. This project is a lot more ambitious and would require state-level buy in. I think we can build out a front-end only mock up as a use-case and to gain experience in user-based design (see above for more details), but it may or may not lead to a bigger project! 🤔

**Comment by werdnanoslen** [comment]
Since this project has been going steady for a while now, would you like to make it an official project repo? @sya

**Comment by TaylorMCook** [comment]
Hi! I am the Operations Director at Farmshare Austin and we have been running the Fresh for Less Mobile Markets for almost two full seasons now (https://farmshareaustin.org/food-access/mobile-market/). I am excited to find this group and if you have any questions for us about the program I am happy to talk! 
Taylor

**Comment by werdnanoslen** [comment]
Welcome @TaylorMCook! Glad you have joined us here. Would you and @sya be interested in meeting up at our meetup this wednesday? https://www.meetup.com/Open-Austin/events/240047057/

**Comment by TaylorMCook** [comment]
Hi @werdnanoslen. I was hoping that I could make it to the meetup tonight but I am not going to be able to this time. Hopefully I can come to another one soon and I am really looking forward to catching up with what y'all are working on!

**Comment by werdnanoslen** [comment]
Ah too bad, have you joined our meetup group? You should get a notification when the next one is coming up when you rsvp. Hope to see you soon!

**Comment by werdnanoslen** [comment]
@sya we miss you at our hack nights! How's progress been on this lately? Anything I can help with?

**Comment by VictoriaODell** [comment]
Just want to follow up with some info that was sent from Austin Eco Network that is relevant to this. 

> [Food/Zero Waste] In Travis County (where Austin is located) 18 percent of the population and 25 percent of the children are food insecure. This means that they don't know where their next meal will come from. Meanwhile, 194.5 million pounds of food (worth more than $208 million) is wasted annually in this city.
> 
> So how do we fix this imbalance? A new group of activists are hoping to create a solution. The Save The Food Coalition is working to create a new city ordinance that will require restaurants and businesses to donate or sell their leftover (but still edible food), instead of just throwing it away or composting it.
> 
> Save The Food Coalition is trying to pass a new ordinance in Austin.
> 
> But wait, isn't this already happening?
> Our city already has a policy that requires food-related business to divert organic waste from the landfill. They can do this in a number of ways, including by donating food, composting, and simply reducing the amount of waste produced in the first place. This is a part of the Universal Recycling Ordinance, which has been popular within the environmental community, but as the Save The Food Coalition sees it, there are even more opportunities to serve the community and reduce waste at the same time. 
> 
> In a Facebook Live interview with the Austin EcoNetwork earlier this week, Save The Food Coalition Founder Allen Schroeder explained that the problem is that the typical grocery store, for example, creates two types of organic waste:
> Food scraps, food that is no longer edible, soiled paper - this is a great candidate for composting
> Food that is still safe to eat, but has been taken off the shelves because of unsightly bruises or because it's slightly past the sell-by-date (but not actually gone bad) - this is food that, as a volunteer, Schroeder already picks up from some local grocery stores and donates to nonprofit organizations that feed the hungry. Now, Schroeder wants to ensure that this edible food is saved and donated at all grocery stores across the city. 
> This whole idea comes back to the Food Waste Hierarchy, a concept often used within the environmental community to ensure that food waste always goes to the highest and best use. 
> 
> The Food Waste Heirarchy
> With so many people in Austin in need of better access to food, Schroeder hopes that the new ordinance will not only reduce the amount of waste that we send to the landfill, but will also fill an important community need. 
> 
> Right now, the Save The Food Coalition is in the research and coalition-building phase. If you would like to learn more about the coalition, or get involved with its efforts, you can check out their website here>>https://www.savethefoodaustin.com/?utm_source=Austin+EcoNewsletter&utm_campaign=3e55370329-EN11%2F9%2F17_SaveFood_RecyclesDay_2Jobs&utm_medium=email&utm_term=0_e376911220-3e55370329-171090565
>

**Comment by mscarey** [comment]
Closing this because the discussion has fizzled out and the group doesn't seem to have settled on which of the 2 problem statements they wanted to work on (SNAP applications or grocery locations).
