### ISSUE TITLE
Texas Bar State Registry

### ISSUE THREAD

**Issue by mscarey** [open-austin/project-ideas#86]
### What problem are we trying to solve?

Putting the Texas State Bar's legal aid referral listings online in a more accessible and current form than the current PDF.

### Who will benefit (directly and indirectly) from this project?

People who need legal help, but aren't able to get access to a print copy of the referral directory and have trouble finding what they need in the PDF.

### Links to any research/data available/articles

The [existing directory (PDF)](https://www.texasbar.com/Content/NavigationMenu/LawyersGivingBack/LegalAccessDivision/ReferralDirectory.pdf). The [Open Referral data standard](docs.openreferral.org).

### What are the next steps (validation, research, coding, design)? 

The State Bar hasn't approved the release of the data yet. Most progress is blocked because of that.

### What help is needed at this time?

Design, planning, database, web development. Also we're interested in setting up a chatbot for searching through the referral listings.

**Comment by mateoclarke** [comment]
Hey @mscarey, @hlupico, have we heard back on how the internal meeting went yet?

**Comment by hlupico** [comment]
@mateoclarke - Katherine is still working with the IT department to get them on board with making the data public. Last week they agreed that they could routinely release a .csv file with the data needed to feed a digital referral directory until the IT department has the time to dedicate to making the data public. Katherine has another meeting set up this week to continue this conversation. 

I would be open to starting a project that could consume the .csv files but I'd like to chat face-to-face about that. My general thought being that we could start with a white label solution, where the data comes from is an implementation detail. 

Would love to hear thoughts from you or anyone who wants to chime in.

**Comment by mateoclarke** [comment]
@hlupico, thanks for the update!

I like that idea. Making it something that could apply to other State Bars service/referral directories would be great. And I could see a solution serving completely different needs. 

There was a past Open Austin project that was basically a registry of non profit service providers in the Digital Inclusion space: https://github.com/DigitalInclusion/digitalatx

And there is another open project idea from the City's Public Information Office. They are looking to redo the Community Registry. #78 

If we designed a "white-label solution" that could accommodate those three use cases, we'd have a pretty robust platform that could be applied to any kind of community/non-profit registry.

**Comment by werdnanoslen** [comment]
@hlupico any updates from your work on this last hack night?

**Comment by hlupico** [comment]
@werdnanoslen posting an update here as a test for the update reminder

**Comment by werdnanoslen** [comment]
Hi y'all, how's this project going? Anything I can help with?

**Comment by mscarey** [comment]
I think the State Bar decided not to release the dataset for the directory,
which caused us to abandon the project before it really got started.

**Comment by werdnanoslen** [comment]
Oh dang. Can we pivot this project to maybe a liberation or data-gathering project, or is it totally lost?

**Comment by mscarey** [comment]
I think without an organization's buy-in, it makes a lot less sense to
gather and release the dataset. There's no obvious way to make our data
more timely than what the bar association has, and most likely it would be
less timely and less authoritative. Maybe we could just refer anyone
interested in this project to #78 "Building a True Community Registry for
Austin."

**Comment by werdnanoslen** [comment]
Sounds good, I'll close this one then. #78  currently doesn't have anyone driving it afaik, so it's marked as abandoned. Do you want to take the lead on that?
