### ISSUE TITLE
Austin Community Organizing (website)

### ISSUE THREAD

**Issue by Glaze-S** [open-austin/project-ideas#87]
### What problem are we trying to solve?
There are many groups organizing in Central Texas, many are first time organizers. it would be useful to have a tool that people can use to help coordinate and collaborate.

### Who will benefit (directly and indirectly) from this project?

Texas constituents at local, state, federal government. Community organizers. Community organizations. Policymakers will also benefit more indirectly, as a result of unified constituent voices and activating previously unheard voices.

### Links to any research/data available/articles

Links here for public data.
American Fact Finder- http://factfinder2.census.gov/
National Historical GIS data- http://www.nhgis.org/
Data.gov- http://catalog.data.gov/dataset
Earth Explorer- http://earthexplorer.usgs.gov/
National GeoSpatial Program- http://www.usgs.gov/ngpo/ (geological, water, environmental)
Tufts Geospatial Data- http://geodata.tufts.edu/
Land and Texas State GIS data- https://olinuris.library.cornell.edu/collections/maps/links/gis-data/us#tx
Behavioral Risk Factors Database- https://www.cdc.gov/brfss/brfssprevalence/index.html and https://chronicdata.cdc.gov/health-area/behavioral-risk-factors
Satellite imagery from GloVis- http://glovis.usgs.gov/

### What are the next steps (validation, research, coding, design)? 

We need more input from organizers about what would work best for them on-the-ground. Then, codign and design.

### What help is needed at this time?

Answer here.

**Comment by mateoclarke** [comment]
Hi @DataloverAustin, It sounds like this project still needs initial research to learn what problems first time organizers experience. Have you done any more research since making this proposal? Do you know what existing tools are solutions this audience is using?

 At this point in time, what work is needed?

**Comment by mateoclarke** [comment]
Hey @DataloverAustin, 

Here's a framework to organizing your research that has been helpful in the past, called the Civic Tech Planning Canvas:
https://www.open-austin.org/civic-tech-canvas/

If you'd like to keep this proposal open, please update us with what research you've done and how people can help.

**Comment by anu007** [comment]
Hello, I am Anu and have a degree in UX Design.I wanted to join the design team, Please let me know do you guys need UX Designer or Researcher?I am open to work on other projects.Thanks

**Comment by mscarey** [comment]
Looks like the discussion ended with no decision about what kind of tool was desired.
