### ISSUE TITLE
Resistance Calendar

### ISSUE THREAD

**Issue by november9** [open-austin/project-ideas#88]
## Web app for defending democracy from the Trump administration 

**[Project Repo](https://github.com/november9/wecansavedemocracy)**

# **UPDATE**
## Efforts on this project have been halted, as the folks involved decided instead to join forces with **http://www.resistancecalendar.org**, which has gotten a ton of traction and is a heavily-visited website, thanks in big part to the media promotion by Michael Moore earlier this year. If you'd like to join us, we could certainly use the help! **https://github.com/ResistanceCalendar/resistance-calendar-frontend**.

****

_Jump to this project's [issues page](https://github.com/november9/wecansavedemocracy/issues) to see how you can contribute_

--- 
_original proposal from 2017-01-26 begins here_

(I couldn't find any mention reading through the documentation in this repo whether or not it was ok to propose projects that are politically partisan in nature, but my apologies in advance if such a project does not fit Open Austin's guidelines).

### What problem are we trying to solve?

Only days into the Trump administration, we are seeing evidence that civil rights, the environment, and global peace are at great risk on account of the administration's extreme policies. While there are a good number of apps that encourage political engagement, those are generally built by well-funded organizations, and as a result need to be bipartisan. This mobile and tablet-friendly web app solves the problem of progressive constituents being overwhelmed with everything that's happening, but not knowing where to begin. 

This app allows you to easily find actions and events sorted by causes as well as time commitment. Once you've created an action list, you can assign dates to all of the actions that are not actual scheduled events, and import your list of actions and events into the calendar of your choice (Google, Apple, Outlook, Yahoo, etc). Now these actions are built into your daily/weekly/monthly routine and you're much more likely to actually carry them out. 

### Who will benefit (directly and indirectly) from this project?
Directly: Progressive constituents, government officials, and candidates
Indirectly: The entire world, as a result of having the undisputed global superpower return to a safe and stable democracy   

### Links to any research/data available/articles

* https://github.com/november9/wecansavedemocracy (I've made a start, design is still very much in a basic format, needs work)
* https://developers.google.com/civic-information/docs/using_api
* https://propublica.github.io/congress-api-docs/

### What are the next steps (validation, research, coding, design)? 

* complete development of a minimum viable product (JavaScript, HTML, CSS)
* polish the design
* determine the best hosting and security solution
* get content 

### What help is needed at this time?

* JavaScript developers who are experienced with, or would like to become experienced with React
* Hosting and network expertise 
* Suggestions for actions and causes
* Data Entry
* Design

**Comment by mateoclarke** [comment]
Thanks for making a submission! Seems like this could be a pretty non partisan solution to a problem for political event organizers and activists.

I really appreciate the work that has gone into the mockups so far. That really helps clarify your vision. https://docs.google.com/drawings/d/18aKq4ts9mo3d7j8q8ND-WAyaTnrhyrEH23iaM0WSb94/edit?usp=sharing

- What user data would be collected for this, if any? 
- Is there admin/user relationship. 
- How much does this get into CRM world?

Thanks
~ mateo

**Comment by november9** [comment]
Thanks @mateoclarke! I suppose it could be non partisan, but I certainly wouldn't want it to be used by folks looking to organize support for a Muslim ban, anti-LGBT legislation, or any other far-right policies. So I suppose anyone who wanted to use this for another cause would have to recreate the back end, since as of right now (don't laugh), I am using WordPress as an API provider, since although I'd like to get as many of the data in via live JSON feed, this would also rely on a number of non-technical volunteers doing data entry at first, and WordPress would make it super-easy for them to do so, and would make it super-easy for us to create contributor accounts as well as creating many different kinds of entities. The goal is to get something live asap, and not having to build an admin panel cuts the scope down by well over 50% in my estimation.  

To answer your questions:
* At first, no data would be collected, or if so, it would be anonymous. I was thinking that people (me at least) are tired of joining yet another social network and having yet another set of login credentials to keep track of. In addition, although it might sound a bit far-fetched, some may be wary of entering identifiable information into an app that promotes political action that opposes the current administration (although the data would be moderated to make sure it's all 100% legal and ethical). Right now, I am storing all of the user's data in localStorage, as this is really designed to be a list of actions you build in one or maybe a few sittings, import into your calendar, and then come back and create a new calendar. Perhaps this is a bit too simplistic, but like I said, I just wanted to get an MVP out there asap. Being the PDF's and Google Docs with action items are making national news right now, even something basic would probably get a lot of exposure even in a fairly "alpha" state.    
* The admin/user relationship would basically be between an admin and individual pre-authorized contributors who could enter events as well as suggested actions. It would be managed via the WordPress back end. 
* Since I wasn't planning on collecting user data, at least at first, it doesn't get into the CRM world at all. I'm really just thinking of this as a fairly basic tool, which, if it catches on, could potentially evolve into a much bigger platform (and if we were to stick with WordPress, it would be easy to expand the platform to include written as well as video content).

Sorry for the wordiness, definitely open to suggestions. :)

**Comment by mateoclarke** [comment]
Very cool. Could you [create some issues on your repo](https://github.com/november9/wecansavedemocracy/issues) with some discrete tasks you'd like help with? That will give us something to point people to.

Also, are you interested in coming to one of our upcoming hack events to collaborate with folks on this? The next one is our Civic Hack Saturday on Feb 4.
https://www.meetup.com/Open-Austin/events/236856863/?

**Comment by november9** [comment]
Yes, I will definitely create some issues with discreet tasks. And I'd love to attend the hack event on Feb 4. I might not be able to stay the entire day, but I've got it on my calendar and looking forward to it very much. 

Thanks!

**Comment by november9** [comment]
OK, repo updated with issues and a much more descriptive README.

**Comment by bripenney** [comment]
I would love to help work on this as a designer. Right now there are a lot of email lists trying to do something like this, but nothing interactive. I'm going to try to come to the hack event on Saturday. What time would you probably be going? You can message me on Slack too @bripenney.

**Comment by ticketsamson** [comment]
This is a great idea. Here is a link to a like-minded checklist: https://docs.google.com/document/d/1THRZKiF9oGQ6a1MBWFVIDHv5a8SuI2vLpIYUfx3Df00/preview

**Comment by november9** [comment]
@bripenney and @ticketsamson  - So great to hear that you guys are interested in the idea! I am shifting my schedule around so I can hopefully be there the whole time on Saturday, from 9am to 2pm.  @bripenney, would love to get your thoughts on the design. I've attached a PDF with what it looks like so far, which is just using Google's Material Design UI library and the library's "dark" theme. I know it's not pretty, but because time is of the essence, using a library like this speeds up development time exponentially. 

So it would be great to keep a lot of the basic elements as they are, and just change the colors, add a header, logo of some sort (the URL I'm using now is WeCanSaveDemocracy.org). 

[wecansavedemocracy-app-work-in-progress.pdf](https://github.com/open-austin/project-ideas/files/743824/wecansavedemocracy-app-work-in-progress.pdf)

I created an issue for this at https://github.com/november9/wecansavedemocracy/issues/1, so I say feel free to assign it to yourself and get started if you like. :)

**Comment by thedeadline** [comment]
I am interested and can help with design, ux/research, and if y'all are interested in making an Android native app. Can reach me hello@isabelleg.me

**Comment by mateoclarke** [comment]
https://www.risestronger.org/

**Comment by amaliebarras** [comment]
@thedeadline Here are all of the [issues](https://github.com/november9/wecansavedemocracy/issues) in the repo if you're ready to ready to hop in and collaborate

**Comment by tgodfrey12** [comment]
I would like to help with this project.  I am currently a web dev student at Galvanize but I have a lot of experience as a developer of non-web languages.  Are you meeting at the Civic Hack night tomorrow?  Do you have room for another developer?

**Comment by bripenney** [comment]
Hey guys, this project is no longer being done through Open Austin. It's part of the Resistance Calendar now with Progressive Coders Network.

**Comment by werdnanoslen** [comment]
@tgodfrey12, judging by Amalie's comment just before yours, I think you'll find a lot of opportunities at their main project repo.

**Comment by werdnanoslen** [comment]
@bripenney how can we best divert interested folks to that project? Is there a landing page that gives an overview?

**Comment by bripenney** [comment]
I think this would be the best place: http://www.progcode.org/. Once you're on the slack channel you can get a lot more info. This is the live site: https://www.resistancecalendar.org/

It's sponsored by Michael Moore which is why it's gotten more traction.

**Comment by werdnanoslen** [comment]
Hi @bripenney & @november9, how are y'all doing on this project? Need any help?

**Comment by werdnanoslen** [comment]
Houston (Sketch City) was recently working on a local version of resistbot https://github.com/sketch-city/project-ideas/issues/103

**Comment by november9** [comment]
@werdnanoslen I just updated this issue's notes to confirm that we did, indeed, join forces with the Resistance Calendar. Come check us out at https://github.com/ResistanceCalendar/resistance-calendar-frontend, the site's getting a lot of traction and we could always use the help!

**Comment by werdnanoslen** [comment]
Gotcha, good luck with your partnership! I renamed this issue so others can find you more easily. Will you still come to Open Austin to work on it?

**Comment by dorono** [comment]
@werdnanoslen I would totally love to(!), but I've gotten super-busy and haven't had a chance to make it down. I will try my damndest though. If it's at all possible, I'd love to find a way to spend a couple of days here: https://www.txdemocrats.org/event/austin-political-hackathon/

**Comment by thedeadline** [comment]
If y'all need a UX designer, hit me up. :)

**Comment by dorono** [comment]
@thedeadline If you want to join the project, just contact Devin at https://github.com/InciteDemocracy.

**Comment by werdnanoslen** [comment]
@dorono we've been listing that event in our announcements for a month or so, so I think you might find some others from Open Austin joining you if you go 👍 

And no problem on the super-busyness, just want to check in every so often. If you need anything let us know

**Comment by anu007** [comment]
Hello, I am Anu and have a degree in UX Design.I wanted to join the design team, Please let me know do you guys need UX Designer or Researcher?I am open to work on other projects.Thanks

**Comment by mscarey** [comment]
Closing because this project has been halted. It was questionable whether the project could  work within Open Austin's nonpartisan policy anyway. Congrats on launching your new iteration of the calendar!
