### ISSUE TITLE
Lead plumbing data requests

### ISSUE THREAD

**Issue by mscarey** [open-austin/project-ideas#89]
### What problem are we trying to solve?

We don't know which buildings/areas in Austin are served by lead pipes, so it's hard for people to evaluate their health risks.

### Who will benefit (directly and indirectly) from this project?

People who want to determine whether the plumbing system serving their home is safe. Also people who want to research schools, workplaces, etc.

### Links to any research/data available/articles

Here's an example of a good [lead disclosure map, from Washington DC](https://geo.dcwater.com/Lead/).

A [Vox article](http://www.vox.com/2016/2/17/11034642/lead-poisoning-flint-statistics-data) with an overview of the issue nationally.

A [recent KXAN article](http://kxan.com/2016/01/27/data-high-lead-levels-detected-in-travis-county-waters/) about lead plumbing in Travis County.

Austin's current [water quality reports](http://austintexas.gov/department/drinking-water-quality-report) and a [2014 water quality report](https://lintvkxan.files.wordpress.com/2016/01/aw2014_austinwaterquality.pdf).

The [TCEQ test result search screen](http://dww2.tceq.texas.gov/DWW/).

The [Austin Water page about lead](http://www.austintexas.gov/page/lead). This says that 90 percent of lead tests of customers' taps showed less than 1 part per billion of lead. There's no known safe level of lead in drinking water, but the EPA limit is 15 parts per billion.

[Instructions for a public record request](http://austintexas.gov/public-information-request) (topic: Water Utility Records). We haven't requested anything yet.

### What are the next steps (validation, research, coding, design)? 

This will probably be mostly a research and policy project. First, we should determine exactly what data is already available to the public about lead positive test results and infrastructure (where lead pipes are located) in Austin/Travis County. Then we can make contact with government agencies to ask for more data, maybe using public records requests. To limit the scope of the project, I think it should cover just lead pipes, not lead paint.

One basic question is whether there are any city-owned or county-owned lead pipes, or whether the only lead pipes are privately owned.

### What help is needed at this time?

Research and policy help.

**Comment by werdnanoslen** [comment]
@mscarey any updates on your research or policy questions? I can help track down some leads to get you going.

**Comment by mscarey** [comment]
The only public records request I've done was to get the results of the AISD campus lead testing (which I think was exclusively of water fountains). The response was in PDFs, and they said the lead levels were below the threshold of 1 part per billion for all but two campuses, Zavala (4.3 ppb) and Barrington (4.8 ppb). When the test result was less than 1 ppb, no other number was reported. For Zavala, the offending water fountain apparently was removed, and subsequent testing at several sites showed less than 1 ppb. I don't know what follow-up there was at Barrington.

[HB 2395](https://openstates.org/tx/bills/85/HB2395/) is pending in the Legislature to require school campus lead testing, but there's a fiscal note that says it would cost $22 million, so that might be an obstacle.

The big [database of lead testing results](http://dww2.tceq.texas.gov/DWW/JSP/SearchDispatch?number=&name=&ActivityStatusCD=All&county=TRAVIS&WaterSystemType=All&SourceWaterType=All&SampleType=LeadandCopperSummaries&begin_date=4%2F5%2F2015&end_date=4%2F5%2F2017&action=Search+For+Water+Systems) is from the TCEQ. It's a little bit obscure, and I'm not sure how to link the test results to locations. I also think KXAN already accomplished that in the article linked above. The data for Austin Water may not have been updated since the KXAN article. I think they just don't test every year.

That still leaves the question of where lead pipes are actually located. I don't think there's anything online that we could use to make a service line map like DC has. We could ask [Austin Water](http://www.austintexas.gov/department/contact-information) what records they have, but I haven't approached them.

**Comment by werdnanoslen** [comment]
@mscarey need any help on this project? I know you're working on InfluenceTX a lot these days, so just checking that your last comment is still the current to-do for this project?

**Comment by mscarey** [comment]
Yeah, I haven't been working on this. I think [this page](http://dww2.tceq.texas.gov/DWW/JSP/PBCUSampleSummaryResults.jsp?tinwsys_is_number=5969&tinwsys_st_code=TX&wsnumber=TX2270001%20%20%20&DWWState=TX&begin_date=&end_date=&counter=0) means there are no new test results in the past few years. I think AISD may have some new test results since our public records request, but I doubt they found any more high lead levels.

**Comment by mscarey** [comment]
No one is actively working on this, and I think it's likely that there's no lead pipe dataset in existence for Austin, so it may not be possible to create anything like DC's map.

**Comment by mscarey** [comment]
I'm closing this in favor of #131
