### ISSUE TITLE
Open States (Sunlight Labs)

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/project-ideas#92]
### The repo for the Texas fork of this project is [here](https://github.com/gregoryfoster/openstates/tree/pupa-tx). If you'd like to contribute to the parent project, check out the [open issues](https://github.com/openstates/openstates/issues/1442)

This is a national project focused on collecting and standardizing state legislative bills with a strong community. 
https://blog.openstates.org/post/adopting-open-states/

There are components of this project in need of adoption including the Texas conversion to the pupa framework. 
https://github.com/openstates/openstates/issues/1442

[Open States, getting started docs.](http://docs.openstates.org/en/latest/contributing/getting-started.html)

This walks you through starting up a Docker environment and scraping legislator data. 
Pulls all of the Texas legislator data down into a MongoDB instance + JSON files in the filesystem.

Contact: @mscarey, @raelam, @gregoryfoster

**Comment by gregoryfoster** [comment]
I've begun the process of converting the Texas scrapers.  Here's the working branch:
https://github.com/gregoryfoster/openstates/tree/pupa-tx

**Comment by werdnanoslen** [comment]
Hi there, how's this project going? I've seen it pop up at our hack nights every so often, so I'd like to give other folks a little more info about the current state of your work. Is your repo and its issues still the most recent work/to-dos, or are there other updates?

**Comment by gregoryfoster** [comment]
Closing this issue as the Pupa Conversion project has been completed.

**Comment by werdnanoslen** [comment]
Neat, good work on your branch @gregoryfoster! I'd love to feature your work on our [projects page](https://www.open-austin.org/projects/). Could you please share a paragraph or so of what the mission/problem was, why you worked on this, what you learned, and how the Open States project was improved?

**Comment by gregoryfoster** [comment]
Thanks, @werdnanoslen, but the credit belongs to @scichelli who picked up my initial work and [completed the vast majority of required functionality](https://github.com/openstates/openstates/pull/1749).  Maybe she would like to answer the questions you pose.

**Comment by scichelli** [comment]
Hi, thanks, I'll answer you in Slack if that's cool.

**Comment by werdnanoslen** [comment]
Posted! https://www.open-austin.org/projects/openstates-texas.html

> The upgrade is complete, so our scraper runs with the new Open States framework, but the logic in the scraper could still be improved, since the legislature publishes their journals in a slightly different format each session. **So if you’d like to contribute, there’s an open issue on GitHub that would love your attention: https://github.com/openstates/openstates/issues/1782**

**Comment by mscarey** [comment]
I believe this is still semi-active because InfluenceTX is using the OpenStates API
