### ISSUE TITLE
Automate project idea policy tasks

### ISSUE THREAD

**Issue by werdnanoslen** [open-austin/project-ideas#98]
Test issue, will delete in an hour or so...

**Comment by werdnanoslen** [comment]
Hi, could someone please post an update (even if it's just 'still working') on this project idea? If we don't hear back in two weeks we will assume this project has been abandoned.

**Comment by hlupico** [comment]
I just posted a comment on the Texas State Bar Registry project (
https://github.com/open-austin/project-ideas/issues/86).

**Comment by werdnanoslen** [comment]
@hlupico heya, this is just a test issue, these are being automatically responded to from my bot https://github.com/open-austin/iced-coffee/issues/247 :)

**Comment by werdnanoslen** [comment]
success!

**Comment by werdnanoslen** [comment]
Hi, could someone please post an update (even if it's just 'still working') on this project idea? If we don't hear back in two weeks we will assume this project has been abandoned.

**Comment by werdnanoslen** [comment]
Hi, could someone please post an update (even if it's just 'still working') on this project idea? If we don't hear back in two weeks we will assume this project has been abandoned.

**Comment by werdnanoslen** [comment]
Hi, could someone please post an update (even if it's just 'still working') on this project idea? If we don't hear back in two weeks we will assume this project has been abandoned.

**Comment by werdnanoslen** [comment]
Hi, could someone please post an update (even if it's just 'still working') on this project idea? If we don't hear back in two weeks we will assume this project has been abandoned.

**Comment by werdnanoslen** [comment]
Hi, could someone please post an update (even if it's just 'still working') on this project idea? If we don't hear back in two weeks we will assume this project has been abandoned.

**Comment by werdnanoslen** [comment]
test

**Comment by werdnanoslen** [comment]
Hi, could someone please post an update (even if it's just 'still working') on this project idea? If we don't hear back in two weeks we will assume this project has been abandoned.
